include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    avoid_web_libraries_in_flutter: ignore
    deprecated_member_use: ignore
    file_names: ignore
    unused_field: ignore
    use_build_context_synchronously: ignore
