import 'package:flutter_worksmart_mobile_app/shared/model/user_model/user_profile.dart';

final List<Map<String, dynamic>> usersFinalData = [
  {
    "uid": "user_winner_777",
    "display_name": "Yun Winner",
    "role_title": "Mobile Developer",
    "password": "password123",
    "gender": "male",
    "profile_url":
        "https://res.cloudinary.com/dwrf0xt1x/image/upload/v1770293036/80d377c6-df66-4732-8fe5-c0fc67741058_x9xxjw.jpg",
    "phone": "096 123 4567",
    "email": "winner.dev@worksmart.kh",
    "office_id": "hq_phnom_penh_01",
    "department_id": "km_it",
    "biometrics": {
      "face_status": "approved",
      "face_count": 3,
      "registered_date": "2023-10-10",
      "face_vectors": [],
    },
    "leave_records": [
      {
        "request_id": "lv_123",
        "type": "annual_leave",
        "start_date": "2023-12-20",
        "end_date": "2023-12-24",
        "reason": "Family vacation",
        "status": "approved",
        "attachment_url": null,
      },
      {
        "request_id": "lv_124",
        "type": "sick_leave",
        "start_date": "2024-01-15",
        "end_date": "2024-01-17",
        "reason": "Flu and fever",
        "status": "pending",
        "attachment_url": "files/medical_note.pdf",
      },
    ],
    "telegram": {
      "is_connected": true,
      "telegram_id": "77889900",
      "telegram_username": "@winner_dev",
    },
    "achievements": {
      "total_medals": 12,
      "performance_score": 98,
      "rank_trend": 2,
      "goal": {
        "title": "goal_hero",
        "desc": "goal_hero_desc",
        "progress_percent": 0.8,
        "days_count": "20/25",
      },
      "badges": [
        {"id": "b1", "key": "early_bird", "is_unlocked": true},
        {"id": "b2", "key": "perfect_month", "is_unlocked": false},
      ],
    },
    "app_settings": {
      "language": "km",
      "theme_mode": "light",
      "notifications_enabled": true,
      "biometric_lock": true,
    },
  },
  {
    "uid": "user_sophy_888",
    "display_name": "Chem Sophy",
    "role_title": "Backend Developer",
    "password": "password123",
    "gender": "female",
    "profile_url": "https://i.pravatar.cc/150?u=6",
    "phone": "097 456 7890",
    "email": "chem.sophy@worksmart.kh",
    "office_id": "hq_phnom_penh_01",
    "department_id": "km_it",
    "biometrics": {
      "face_status": "uninitialized",
      "face_count": 2,
      "registered_date": "2023-09-15",
      "face_vectors": [],
    },
    "leave_records": [
      {
        "request_id": "lv_125",
        "type": "annual_leave",
        "start_date": "2023-12-24",
        "end_date": "2023-12-31",
        "reason": "Holiday break",
        "status": "approved",
        "attachment_url": null,
      },
      {
        "request_id": "lv_126",
        "type": "sick_leave",
        "start_date": "2024-02-10",
        "end_date": "2024-02-12",
        "reason": "Migraine and nausea",
        "status": "pending",
        "attachment_url": "files/medical_note.pdf",
      },
    ],
    "telegram": {
      "is_connected": true,
      "telegram_id": "88990011",
      "telegram_username": "@chem_sophy",
    },
    "achievements": {
      "total_medals": 18,
      "performance_score": 88,
      "rank_trend": 1,
      "goal": {
        "title": "goal_hero",
        "desc": "goal_hero_desc",
        "progress_percent": 0.95,
        "days_count": "24/25",
      },
      "badges": [
        {"id": "b1", "key": "early_bird", "is_unlocked": true},
        {"id": "b2", "key": "perfect_month", "is_unlocked": true},
      ],
    },
    "app_settings": {
      "language": "km",
      "theme_mode": "dark",
      "notifications_enabled": true,
      "biometric_lock": true,
    },
  },
  {
    "uid": "user_developer_889",
    "display_name": "Sokea Devv",
    "role_title": "Backend Developer",
    "password": "password123",
    "profile_url": "https://i.pravatar.cc/150?u=6",
    "phone": "097 456 7890",
    "email": "sokea.dev@worksmart.kh",
    "office_id": "hq_phnom_penh_01",
    "department_id": "km_it",
    "biometrics": {
      "face_status": "approved",
      "face_count": 2,
      "registered_date": "2023-09-15",
      "face_vectors": [],
    },
    "leave_records": [
      {
        "request_id": "lv_127",
        "type": "annual_leave",
        "start_date": "2023-12-24",
        "end_date": "2023-12-31",
        "reason": "Holiday break",
        "status": "approved",
        "attachment_url": null,
      },
      {
        "request_id": "lv_128",
        "type": "sick_leave",
        "start_date": "2024-02-10",
        "end_date": "2024-02-12",
        "reason": "Migraine and nausea",
        "status": "pending",
        "attachment_url": "files/medical_note.pdf",
      },
    ],
    "telegram": {
      "is_connected": true,
      "telegram_id": "88990011",
      "telegram_username": "@sokea_dev",
    },
    "achievements": {
      "total_medals": 18,
      "performance_score": 95,
      "rank_trend": 1,
      "goal": {
        "title": "goal_hero",
        "desc": "goal_hero_desc",
        "progress_percent": 0.95,
        "days_count": "24/25",
      },
      "badges": [
        {"id": "b1", "key": "early_bird", "is_unlocked": true},
        {"id": "b2", "key": "perfect_month", "is_unlocked": true},
      ],
    },
    "app_settings": {"notifications_enabled": true, "biometric_lock": true},
  },
];

final List<UserProfile> usersFinalProfiles = usersFinalData
    .map(UserProfile.fromJson)
    .toList();
