import 'package:flutter_worksmart_mobile_app/shared/model/user_model/user_profile.dart';

final List<Map<String, dynamic>> usersFinalData = [
  {
    "uid": "user_winner_777",
    "display_name": "Yun Winner",
    "role_title": "Mobile Developer",
    "password": "password123",
    "gender": "male",
    "profile_url":
        "https://res.cloudinary.com/dwrf0xt1x/image/upload/v1772549669/winner-yun.jpg",
    "phone": "096 123 4567",
    "email": "winner.dev@worksmart.kh",
    "office_id": "hq_phnom_penh_01",
    "department_id": "km_it",
    "biometrics": {
      "face_status": "uninitialized",
      "face_count": 3,
      "registered_date": "2023-10-10",
      "face_image_urls": [],
      "face_vectors": [],
    },
    "leave_records": [
      {
        "request_id": "lv_125",
        "type": "annual_leave",
        "start_date": "2024-02-10",
        "end_date": "2024-02-14",
        "reason": "Travel with family",
        "status": "approved",
        "attachment_url": null,
      },
      {
        "request_id": "lv_126",
        "type": "sick_leave",
        "start_date": "2024-03-05",
        "end_date": "2024-03-06",
        "reason": "Food poisoning",
        "status": "approved",
        "attachment_url": "files/medical_note.pdf",
      },
      {
        "request_id": "lv_127",
        "type": "annual_leave",
        "start_date": "2024-03-20",
        "end_date": "2024-03-20",
        "reason": "Personal matters",
        "status": "pending",
        "attachment_url": null,
      },
      {
        "request_id": "lv_128",
        "type": "annual_leave",
        "start_date": "2024-04-12",
        "end_date": "2024-04-16",
        "reason": "New Year holiday",
        "status": "approved",
        "attachment_url": null,
      },
      {
        "request_id": "lv_129",
        "type": "sick_leave",
        "start_date": "2024-05-02",
        "end_date": "2024-05-03",
        "reason": "Migraine treatment",
        "status": "rejected",
        "attachment_url": "files/medical_note.pdf",
      },
      {
        "request_id": "lv_130",
        "type": "annual_leave",
        "start_date": "2024-06-01",
        "end_date": "2024-08-31",
        "reason": "Maternity leave period",
        "status": "approved",
        "attachment_url": null,
      },
      {
        "request_id": "lv_131",
        "type": "annual_leave",
        "start_date": "2024-07-22",
        "end_date": "2024-07-25",
        "reason": "Family event",
        "status": "pending",
        "attachment_url": null,
      },
    ],
    "telegram": {
      "is_connected": false,
      "telegram_id": "77889900",
      "telegram_username": "@winner_dev",
    },
    "achievements": {
      "total_medals": 1,
      "performance_score": 98,
      "rank_trend": 2,
      "goal": {
        "title": "goal_hero",
        "desc": "goal_hero_desc",
        "progress_percent": 0.8,
        "days_count": "20/25",
      },
      "badges": [
        {"id": "b1", "key": "early_bird", "is_unlocked": true},
        {"id": "b2", "key": "perfect_month", "is_unlocked": false},
      ],
    },
    "app_settings": {
      "language": "km",
      "theme_mode": "light",
      "notifications_enabled": true,
      "biometric_lock": true,
    },
  },
  {
    "uid": "user_sophy_888",
    "display_name": "Chem Sophy",
    "role_title": "Backend Developer",
    "password": "password123",
    "gender": "female",
    "profile_url":
        "https://res.cloudinary.com/dwrf0xt1x/image/upload/v1772548812/known%20profile.webp",
    "phone": "097 456 7890",
    "email": "chem.sophy@worksmart.kh",
    "office_id": "hq_phnom_penh_01",
    "department_id": "km_it",
    "biometrics": {
      "face_status": "uninitialized",
      "face_count": 2,
      "registered_date": "2023-09-15",
      "face_image_urls": [],
      "face_vectors": [],
    },
    "leave_records": [
      {
        "request_id": "lv_125",
        "type": "annual_leave",
        "start_date": "2023-12-24",
        "end_date": "2023-12-31",
        "reason": "Holiday break",
        "status": "approved",
        "attachment_url": null,
      },
      {
        "request_id": "lv_126",
        "type": "sick_leave",
        "start_date": "2024-02-10",
        "end_date": "2024-02-12",
        "reason": "Migraine and nausea",
        "status": "pending",
        "attachment_url": "files/medical_note.pdf",
      },
    ],
    "telegram": {
      "is_connected": true,
      "telegram_id": "88990011",
      "telegram_username": "@chem_sophy",
    },
    "achievements": {
      "total_medals": 18,
      "performance_score": 88,
      "rank_trend": 1,
      "goal": {
        "title": "goal_hero",
        "desc": "goal_hero_desc",
        "progress_percent": 0.95,
        "days_count": "24/25",
      },
      "badges": [
        {"id": "b1", "key": "early_bird", "is_unlocked": true},
        {"id": "b2", "key": "perfect_month", "is_unlocked": true},
      ],
    },
    "app_settings": {
      "language": "km",
      "theme_mode": "dark",
      "notifications_enabled": true,
      "biometric_lock": true,
    },
  },
  {
    "uid": "user_developer_889",
    "display_name": "Sokea Devv",
    "role_title": "Backend Developer",
    "password": "password123",
    "profile_url":
        "https://res.cloudinary.com/dwrf0xt1x/image/upload/v1772548812/known%20profile.webp",
    "phone": "097 456 7890",
    "email": "sokea.dev@worksmart.kh",
    "office_id": "hq_phnom_penh_01",
    "department_id": "km_it",
    "biometrics": {
      "face_status": "approved",
      "face_count": 2,
      "registered_date": "2023-09-15",
      "face_image_urls": [
        "https://i.pravatar.cc/320?img=11",
        "https://i.pravatar.cc/320?img=12",
      ],
      "face_vectors": [],
    },
    "leave_records": [
      {
        "request_id": "lv_127",
        "type": "annual_leave",
        "start_date": "2023-12-24",
        "end_date": "2023-12-31",
        "reason": "Holiday break",
        "status": "approved",
        "attachment_url": null,
      },
      {
        "request_id": "lv_128",
        "type": "sick_leave",
        "start_date": "2024-02-10",
        "end_date": "2024-02-12",
        "reason": "Migraine and nausea",
        "status": "pending",
        "attachment_url": "files/medical_note.pdf",
      },
    ],
    "telegram": {
      "is_connected": true,
      "telegram_id": "88990011",
      "telegram_username": "@sokea_dev",
    },
    "achievements": {
      "total_medals": 18,
      "performance_score": 95,
      "rank_trend": 1,
      "goal": {
        "title": "goal_hero",
        "desc": "goal_hero_desc",
        "progress_percent": 0.95,
        "days_count": "24/25",
      },
      "badges": [
        {"id": "b1", "key": "early_bird", "is_unlocked": true},
        {"id": "b2", "key": "perfect_month", "is_unlocked": true},
      ],
    },
    "app_settings": {"notifications_enabled": true, "biometric_lock": true},
  },
  {
    "uid": "user_sambath_890",
    "display_name": "Sambath",
    "role_title": "Frontend Developer",
    "password": "password123",
    "gender": "male",
    "profile_url":
        "https://res.cloudinary.com/dwrf0xt1x/image/upload/v1772548812/known%20profile.webp",
    "phone": "098 765 4321",
    "email": "sambath@worksmart.kh",
    "office_id": "hq_phnom_penh_01",
    "department_id": "km_it",
    "biometrics": {
      "face_status": "approved",
      "face_count": 3,
      "registered_date": "2023-08-20",
      "face_image_urls": [
        "https://i.pravatar.cc/320?img=13",
        "https://i.pravatar.cc/320?img=14",
        "https://i.pravatar.cc/320?img=15",
      ],
      "face_vectors": [],
    },
    "leave_records": [
      {
        "request_id": "lv_129",
        "type": "annual_leave",
        "start_date": "2024-03-10",
        "end_date": "2024-03-15",
        "reason": "Personal trip",
        "status": "approved",
        "attachment_url": null,
      },
    ],
    "telegram": {
      "is_connected": true,
      "telegram_id": "99112233",
      "telegram_username": "@sambath",
    },
    "achievements": {
      "total_medals": 12,
      "performance_score": 92,
      "rank_trend": 1,
      "goal": {
        "title": "goal_hero",
        "desc": "goal_hero_desc",
        "progress_percent": 0.85,
        "days_count": "21/25",
      },
      "badges": [
        {"id": "b1", "key": "early_bird", "is_unlocked": true},
        {"id": "b2", "key": "perfect_month", "is_unlocked": false},
      ],
    },
    "app_settings": {
      "language": "km",
      "theme_mode": "light",
      "notifications_enabled": true,
      "biometric_lock": true,
    },
  },
  {
    "uid": "user_sopheak_891",
    "display_name": "Sopheak",
    "role_title": "UI/UX Designer",
    "password": "password123",
    "gender": "male",
    "profile_url":
        "https://res.cloudinary.com/dwrf0xt1x/image/upload/v1772548812/known%20profile.webp",
    "phone": "099 876 5432",
    "email": "sopheak@worksmart.kh",
    "office_id": "hq_phnom_penh_01",
    "department_id": "km_design",
    "biometrics": {
      "face_status": "approved",
      "face_count": 2,
      "registered_date": "2023-07-15",
      "face_image_urls": [
        "https://i.pravatar.cc/320?img=16",
        "https://i.pravatar.cc/320?img=17",
      ],
      "face_vectors": [],
    },
    "leave_records": [
      {
        "request_id": "lv_130",
        "type": "sick_leave",
        "start_date": "2024-04-01",
        "end_date": "2024-04-02",
        "reason": "Common cold",
        "status": "approved",
        "attachment_url": "files/medical_note.pdf",
      },
    ],
    "telegram": {
      "is_connected": true,
      "telegram_id": "00334455",
      "telegram_username": "@sopheak",
    },
    "achievements": {
      "total_medals": 15,
      "performance_score": 89,
      "rank_trend": 2,
      "goal": {
        "title": "goal_hero",
        "desc": "goal_hero_desc",
        "progress_percent": 0.75,
        "days_count": "19/25",
      },
      "badges": [
        {"id": "b1", "key": "early_bird", "is_unlocked": true},
        {"id": "b2", "key": "perfect_month", "is_unlocked": true},
      ],
    },
    "app_settings": {
      "language": "km",
      "theme_mode": "dark",
      "notifications_enabled": true,
      "biometric_lock": true,
    },
  },
  {
    "uid": "user_tepy_892",
    "display_name": "Tepy",
    "role_title": "QA Engineer",
    "password": "password123",
    "gender": "female",
    "profile_url":
        "https://res.cloudinary.com/dwrf0xt1x/image/upload/v1772548812/tepy.jpg",
    "phone": "089 234 5678",
    "email": "tepy@worksmart.kh",
    "office_id": "hq_phnom_penh_01",
    "department_id": "km_qa",
    "biometrics": {
      "face_status": "approved",
      "face_count": 3,
      "registered_date": "2023-06-10",
      "face_image_urls": [
        "https://i.pravatar.cc/320?img=18",
        "https://i.pravatar.cc/320?img=19",
        "https://i.pravatar.cc/320?img=20",
      ],
      "face_vectors": [],
    },
    "leave_records": [
      {
        "request_id": "lv_131",
        "type": "annual_leave",
        "start_date": "2024-05-20",
        "end_date": "2024-05-25",
        "reason": "Summer vacation",
        "status": "pending",
        "attachment_url": null,
      },
    ],
    "telegram": {
      "is_connected": true,
      "telegram_id": "11556677",
      "telegram_username": "@tepy",
    },
    "achievements": {
      "total_medals": 20,
      "performance_score": 94,
      "rank_trend": 1,
      "goal": {
        "title": "goal_hero",
        "desc": "goal_hero_desc",
        "progress_percent": 0.90,
        "days_count": "23/25",
      },
      "badges": [
        {"id": "b1", "key": "early_bird", "is_unlocked": true},
        {"id": "b2", "key": "perfect_month", "is_unlocked": true},
      ],
    },
    "app_settings": {
      "language": "km",
      "theme_mode": "light",
      "notifications_enabled": true,
      "biometric_lock": true,
    },
  },
  {
    "uid": "user_kimchhay_893",
    "display_name": "Kimchhay",
    "role_title": "DevOps Engineer",
    "password": "password123",
    "gender": "male",
    "profile_url":
        "https://res.cloudinary.com/dwrf0xt1x/image/upload/v1772548812/kimchhay.jpg",
    "phone": "088 345 6789",
    "email": "kimchhay@worksmart.kh",
    "office_id": "hq_phnom_penh_01",
    "department_id": "km_it",
    "biometrics": {
      "face_status": "approved",
      "face_count": 2,
      "registered_date": "2023-05-05",
      "face_image_urls": [
        "https://i.pravatar.cc/320?img=21",
        "https://i.pravatar.cc/320?img=22",
      ],
      "face_vectors": [],
    },
    "leave_records": [
      {
        "request_id": "lv_132",
        "type": "sick_leave",
        "start_date": "2024-06-15",
        "end_date": "2024-06-16",
        "reason": "Dental appointment",
        "status": "approved",
        "attachment_url": null,
      },
    ],
    "telegram": {
      "is_connected": false,
      "telegram_id": "22778899",
      "telegram_username": "@kimchhay",
    },
    "achievements": {
      "total_medals": 16,
      "performance_score": 91,
      "rank_trend": 3,
      "goal": {
        "title": "goal_hero",
        "desc": "goal_hero_desc",
        "progress_percent": 0.80,
        "days_count": "20/25",
      },
      "badges": [
        {"id": "b1", "key": "early_bird", "is_unlocked": true},
        {"id": "b2", "key": "perfect_month", "is_unlocked": false},
      ],
    },
    "app_settings": {
      "language": "km",
      "theme_mode": "dark",
      "notifications_enabled": true,
      "biometric_lock": false,
    },
  },
  {
    "uid": "user_fistar_894",
    "display_name": "Fistar",
    "role_title": "Product Manager",
    "password": "password123",
    "gender": "male",
    "profile_url":
        "https://res.cloudinary.com/dwrf0xt1x/image/upload/v1772548812/fistar.jpg",
    "phone": "087 456 7890",
    "email": "fistar@worksmart.kh",
    "office_id": "hq_phnom_penh_01",
    "department_id": "km_product",
    "biometrics": {
      "face_status": "approved",
      "face_count": 3,
      "registered_date": "2023-04-01",
      "face_image_urls": [
        "https://i.pravatar.cc/320?img=23",
        "https://i.pravatar.cc/320?img=24",
        "https://i.pravatar.cc/320?img=25",
      ],
      "face_vectors": [],
    },
    "leave_records": [
      {
        "request_id": "lv_133",
        "type": "annual_leave",
        "start_date": "2024-07-10",
        "end_date": "2024-07-17",
        "reason": "Family time",
        "status": "approved",
        "attachment_url": null,
      },
    ],
    "telegram": {
      "is_connected": true,
      "telegram_id": "33990011",
      "telegram_username": "@fistar",
    },
    "achievements": {
      "total_medals": 22,
      "performance_score": 96,
      "rank_trend": 1,
      "goal": {
        "title": "goal_hero",
        "desc": "goal_hero_desc",
        "progress_percent": 0.95,
        "days_count": "24/25",
      },
      "badges": [
        {"id": "b1", "key": "early_bird", "is_unlocked": true},
        {"id": "b2", "key": "perfect_month", "is_unlocked": true},
      ],
    },
    "app_settings": {
      "language": "km",
      "theme_mode": "light",
      "notifications_enabled": true,
      "biometric_lock": true,
    },
  },
];

final List<UserProfile> usersFinalProfiles = usersFinalData
    .map(UserProfile.fromJson)
    .toList();
