import 'package:flutter_worksmart_mobile_app/config/language_manager.dart';

class AppStrings {
  static String get currentLang => LanguageManager().locale;

  static const Map<String, Map<String, String>> data = {
    'en': {
      //menu bottomAppbar
      'home_menu': 'Home',
      'atd_menu': 'Attendent',
      'leave_menu': 'Leave',
      'profile_menu': 'Profile',

      // Auth Screen
      'logging_in_employee': 'Logging in to Employee account...',
      'logging_in_admin': 'Logging in to Admin account...',
      'smart_hr_system': 'Smart HR Management System',
      'admin_dashboard': 'Admin Dashboard',
      'welcome': 'Welcome',
      'admin_login_title': 'Admin Login',
      'smart_hr_management': 'Smart HR Management',
      'advanced_access': 'Advanced Access',
      'login_subtitle_employee': 'Log in to manage attendance and payroll',
      'login_subtitle_admin': 'Please verify your admin identity',
      'employee_tab': 'Employee',
      'admin_tab': 'Admin',
      'username_or_id': 'Username or ID',
      'admin_id': 'Admin ID',
      'enter_id_hint': 'Enter ID',
      'enter_id_error': 'Please enter Username or ID',
      'password': 'Password',
      'enter_password_hint': 'Enter Password',
      'enter_password_error': 'Please enter password',
      'password_length_error': 'Password must be at least 6 characters',
      'login_button': 'Login',
      'admin_login_button': 'Login as Admin',
      'forgot_password': 'Forgot Password?',
      'app_version': 'WorkSmart v1.0 • ',

      "forgot_password_desc":
          "Please enter your email address to receive a verification code.",
      "email_label": "Email Address",
      "enter_email_error": "Please enter your email",
      "invalid_email_error": "Invalid email format",
      "send_button": "Send Code",
      "verify_title": "Verify Code",
      "otp_message": "We have sent a 4-digit code to your email address.",
      "verify_button": "Verify",
      "resend_code": "Resend Code",
      "verifying": "Verifying...",
      "otp_length_error": "Please enter all 4 digits",
      "reset_password_title": "Reset Password",
      "reset_password_subtitle": "Create a strong new password",
      "new_password_label": "New Password",
      "new_password_hint": "Enter new password",
      "confirm_password_label": "Confirm Password",
      "confirm_password_hint": "Re-enter new password",
      "password_empty_error": "Please enter password",

      "password_mismatch_error": "Passwords do not match",
      "change_password_button": "Change Password",
      "success_title": "Success!",
      "success_message": "Your password has been changed successfully.",
      "back_to_login": "Back to Login",

      // Tutorial Screen
      'skip': 'Skip',
      'start': 'Start',
      'next': 'Next',
      'tutorial_title_1': 'Smart Attendance Management',
      'tutorial_subtitle_1': 'Track employee attendance safely and efficiently',
      'tutorial_title_2': 'Anti-Fraud Technology',
      'tutorial_subtitle_2':
          'Verify GPS location and live photo to ensure accuracy',
      'tutorial_title_3': 'Increase Work Efficiency',
      'tutorial_subtitle_3':
          'Achieve achievements and good ranking in the company',

      // Homepage
      'greeting': 'Good Morning,',
      'safety': 'Safety',
      'greet_pronoun_man': 'Mr',
      'greet_pronoun_woman': 'Ms',
      'check_in': 'In',
      'check_out': 'Out',
      'work_hours': 'Hours',
      'current_loc': 'Current Location',
      'office_name': 'Phnom Penh Office',
      'leave_question': 'Time to leave work?',
      'in_range': 'In Range',
      'scan_out': 'Scan to Check Out',
      'annual_leave': 'Annual Leave',
      'sick_leave': 'Sick Leave',
      'employee_title': 'Employee of the Month',
      'view_all': 'View All',
      'role_trainer': 'Trainer',
      'role_ios': 'iOS Developer',
      'role_designer': 'Designer',
      'days': 'Days',

      'office_zone': 'Office Zone',
      'outside_zone': 'Outside Zone',
      'gps_status': 'GPS Status',
      'ready_to_scan': 'Ready to Scan',
      'too_far': 'Too Far',
      'distance': 'Distance',
      'get_directions': 'Get Directions',

      // Attd screen display
      'my_stats': 'My Statistics',
      'attendance_rate': 'Attendance Rate',
      'present': 'Present',
      'late': 'Late',
      'absent': 'Absent',
      'monthly_trend': 'Monthly Attendance Trends',
      'all_shifts': 'All Shifts',
      'monthly_attendance': 'Attendance for September',
      'attendance_details': 'Attendance Details',
      'check_in_title': 'Check-In',
      'check_out_title': 'Check-Out',
      'total_hours': 'Total Work Hours',
      'equal_to': 'Equal to',
      'one_full_day': '1 Full Day',
      'on_time': 'On Time',
      'location_label': 'Location',
      'phnom_penh': 'Phnom Penh',

      // Months (All 12)
      'month_jan': 'Jan',
      'month_feb': 'Feb',
      'month_mar': 'Mar',
      'month_apr': 'Apr',
      'month_may': 'May',
      'month_jun': 'Jun',
      'month_jul': 'Jul',
      'month_aug': 'Aug',
      'month_sep': 'Sep',
      'month_oct': 'Oct',
      'month_nov': 'Nov',
      'month_dec': 'Dec',

      // Leaderboard Screen
      'top_rankings': 'Top Rankings',
      'monthly': 'Monthly',
      'yearly': 'Yearly',
      'next_rankings': 'Next Rankings',
      'average_score': 'Average Score',
      'next_goal': 'Next Goal',
      'goal_description': 'Reach 95% to receive a bronze medal',
      'achievements': 'Achievements',
      'it_department': 'IT Department',
      'acc_department': 'Accounting Department',
      'admin_department': 'Admin Department',

      // in callender
      'no_data': 'No Data',
      'total_work_hours': 'Total Work Hours',
      'attendance_calendar_title': 'Attendance Calendar',
      'download_report': 'Downloading report...',
      'day_label': 'Day',
      'avg_attendance': 'Average Attendance',

      //face scanner screen
      'face_scan_title': 'Please place your face in the circle',
      'face_scan_step': 'Step 2: Scan Face',
      'live_status': 'LIVE',
      'switch_camera': 'Switch Camera',
      'ensure_light': 'Ensure enough light',
      'scan_success': 'Scan Success!',
      'camera_error': 'Camera Error',
    },
    'km': {
      //menu bottomAppbar
      'home_menu': 'ទំព័រដើម',
      'atd_menu': 'វត្តមាន',
      'leave_menu': 'ច្បាប់ឈប់សម្រាក',
      'profile_menu': 'ប្រវត្តិរូប',

      // Auth Screen
      'logging_in_employee': 'កំពុងចូលក្នុងគណនីបុគ្គលិក...',
      'logging_in_admin': 'កំពុងចូលក្នុងគណនីអ្នកគ្រប់គ្រង...',
      'smart_hr_system': 'ប្រព័ន្ធគ្រប់គ្រងបុគ្គលិកវ័យឆ្លាត',
      'admin_dashboard': 'ផ្ទាំងគ្រប់គ្រងអ្នកគ្រប់គ្រង',
      'welcome': 'សូមស្វាគមន៍',
      'admin_login_title': 'ចូលជា Admin',
      'smart_hr_management': 'គ្រប់គ្រងធនធានមនុស្សបែបឆ្លាតវៃ',
      'advanced_access': 'ការចូលប្រើប្រាស់កម្រិតខ្ពស់',
      'login_subtitle_employee':
          'ចូលប្រព័ន្ធដើម្បីគ្រប់គ្រងវត្តមាន និងប្រាក់បៀវត្សរ៍',
      'login_subtitle_admin': 'សូមផ្ទៀងផ្ទាត់អត្តសញ្ញាណអ្នកគ្រប់គ្រងរបស់អ្នក',
      'employee_tab': 'បុគ្គលិក',
      'admin_tab': 'អ្នកគ្រប់គ្រង',
      'username_or_id': 'ឈ្មោះគណនី ឬ លេខសម្គាល់',
      'admin_id': 'គណនីអ្នកគ្រប់គ្រង (Admin ID)',
      'enter_id_hint': 'បញ្ចូលលេខសម្គាល់',
      'enter_id_error': 'សូមបញ្ចូលឈ្មោះគណនី ឬ លេខសម្គាល់',
      'password': 'ពាក្យសម្ងាត់',
      'enter_password_hint': 'បញ្ចូលពាក្យសម្ងាត់',
      'enter_password_error': 'សូមបញ្ចូលពាក្យសម្ងាត់',
      'password_length_error': 'ពាក្យសម្ងាត់ត្រូវមានយ៉ាងតិច ៦ ខ្ទង់',
      'login_button': 'ចូលប្រើប្រាស់',
      'admin_login_button': 'ចូលក្នុងនាមជា Admin',
      'forgot_password': 'ភ្លេចពាក្យសម្ងាត់?',
      'app_version': 'WorkSmart v1.0 • ',

      "forgot_password_desc":
          "សូមបញ្ចូលអាសយដ្ឋានអ៊ីមែលរបស់អ្នក ដើម្បីទទួលបានលេខកូដផ្ទៀងផ្ទាត់។",
      "email_label": "អាសយដ្ឋានអ៊ីមែល",
      "enter_email_error": "សូមបញ្ចូលអ៊ីមែលរបស់អ្នក",
      "invalid_email_error": "ទម្រង់អ៊ីមែលមិនត្រឹមត្រូវ",
      "send_button": "ផ្ញើលេខកូដ",
      "verify_title": "ផ្ទៀងផ្ទាត់កូដ",
      "otp_message": "យើងបានផ្ញើលេខកូដ ៤ ខ្ទង់ទៅកាន់អ៊ីមែលរបស់អ្នក។",
      "verify_button": "ផ្ទៀងផ្ទាត់",
      "resend_code": "ផ្ញើកូដម្តងទៀត",
      "verifying": "កំពុងផ្ទៀងផ្ទាត់...",
      "otp_length_error": "សូមបញ្ចូលកូដឱ្យបានគ្រប់ ៤ ខ្ទង់",
      "reset_password_title": "ប្តូរលេខសម្ងាត់",
      "reset_password_subtitle": "បង្កើតលេខសម្ងាត់ថ្មីដែលរឹងមាំ",
      "new_password_label": "លេខសម្ងាត់ថ្មី",
      "new_password_hint": "បញ្ចូលលេខសម្ងាត់ថ្មី",
      "confirm_password_label": "បញ្ជាក់លេខសម្ងាត់",
      "confirm_password_hint": "បញ្ចូលលេខសម្ងាត់ម្តងទៀត",
      "password_empty_error": "សូមបញ្ចូលលេខសម្ងាត់",
      "password_mismatch_error": "លេខសម្ងាត់មិនត្រូវគ្នា",
      "change_password_button": "ផ្លាស់ប្តូរលេខសម្ងាត់",
      "success_title": "ជោគជ័យ!",
      "success_message": "លេខសម្ងាត់របស់អ្នកត្រូវបានផ្លាស់ប្តូររួចរាល់ហើយ។",
      "back_to_login": "ត្រឡប់ទៅទំព័រចូល",

      // Tutorial Screen
      'skip': 'រំលង',
      'start': 'ចាប់ផ្តើម',
      'next': 'បន្ទាប់',
      'tutorial_title_1': 'គ្រប់គ្រងវត្តមានដោយឆ្លាតវៃ',
      'tutorial_subtitle_1':
          'តាមដានវត្តមានបុគ្គលិកដោយសុវត្ថិភាព និងប្រសិទ្ធភាព',
      'tutorial_title_2': 'បច្ចេកវិទ្យាការពារការបន្លំ',
      'tutorial_subtitle_2':
          'ផ្ទៀងផ្ទាត់ទីតាំង GPS និងថតរូបផ្ទាល់ ដើម្បីធានាភាពត្រឹមត្រូវ',
      'tutorial_title_3': 'បង្កើនប្រសិទ្ធភាពការងារ',
      'tutorial_subtitle_3': 'ទទួលបានសមិទ្ធផល និងចំណាត់ថ្នាក់ល្អក្នុងក្រុមហ៊ុន',

      // Homepage
      'greeting': 'អរុណសួស្តី,',
      'safety': 'សុវត្ថិភាព',
      'check_in': 'ចូល',
      'check_out': 'ចេញ',
      'work_hours': 'ម៉ោង',
      'greet_pronoun_man': 'លោក',
      'greet_pronoun_woman': 'លោកស្រី',
      'current_loc': 'ទីតាំងបច្ចុប្បន្ន',
      'office_name': 'ការិយាល័យភ្នំពេញ',
      'leave_question': 'ដល់ពេលចេញពីធ្វើការ?',
      'in_range': 'ក្នុងទីតាំង',
      'scan_out': 'ចុះវត្តមានចេញ',
      'annual_leave': 'ច្បាប់ប្រចាំឆ្នាំ',
      'sick_leave': 'ច្បាប់ឈឺ',
      'employee_title': 'បុគ្គលិកឆ្នើម',
      'view_all': 'មើលទាំងអស់',
      'role_trainer': 'គ្រូបណ្តុះបណ្តាល',
      'role_ios': 'អ្នកអភិវឌ្ឍន៍ iOS',
      'role_designer': 'អ្នករចនា',
      'days': 'ថ្ងៃ',

      'office_zone': 'ក្នុងតំបន់ការិយាល័យ',
      'outside_zone': 'ក្រៅតំបន់ការិយាល័យ',
      'gps_status': 'ស្ថានភាព GPS',
      'ready_to_scan': 'អាចស្កេនបាន',
      'too_far': 'នៅឆ្ងាយពេក',
      'distance': 'ចម្ងាយ',
      'get_directions': 'នាំផ្លូវទៅកាន់ការិយាល័យ',

      // Attd screen display
      'my_stats': 'ស្ថិតិរបស់ខ្ញុំ',
      'attendance_rate': 'អត្រាវត្តមាន',
      'present': 'វត្តមាន',
      'late': 'មកយឺត',
      'absent': 'អវត្តមាន',
      'monthly_trend': 'និន្នាការវត្តមានប្រចាំខែ',
      'all_shifts': 'គ្រប់វេន',
      'monthly_attendance': 'វត្តមានប្រចាំខែកញ្ញា',
      'attendance_details': 'ព័ត៌មានលម្អិតនៃវត្តមាន',
      'check_in_title': 'ការចុះវត្តមានចូល',
      'check_out_title': 'ការចុះវត្តមានចេញ',
      'total_hours': 'សរុបម៉ោងការងារ',
      'equal_to': 'ស្មើនឹង',
      'one_full_day': '១ ថ្ងៃពេញ',
      'on_time': 'ទាន់ពេល',
      'location_label': 'ទីតាំង',
      'phnom_penh': 'ការិយាល័យកណ្ដាល',

      // Months (All 12)
      'month_jan': 'មករា',
      'month_feb': 'កុម្ភៈ',
      'month_mar': 'មីនា',
      'month_apr': 'មេសា',
      'month_may': 'ឧសភា',
      'month_jun': 'មិថុនា',
      'month_jul': 'កក្កដា',
      'month_aug': 'សីហា',
      'month_sep': 'កញ្ញា',
      'month_oct': 'តុលា',
      'month_nov': 'វិច្ឆិកា',
      'month_dec': 'ធ្នូ',

      // Leaderboard Screen
      'top_rankings': 'ចំណាត់ថ្នាក់បុគ្គលិកឆ្នើម',
      'monthly': 'ប្រចាំខែ',
      'yearly': 'ប្រចាំឆ្នាំ',
      'next_rankings': 'ចំណាត់ថ្នាក់បន្ទាប់',
      'average_score': 'មធ្យមភាគពិន្ទុ',
      'next_goal': 'គោលដៅបន្ទាប់',
      'goal_description': 'ឈានដល់ ៩៥% ដើម្បីទទួលបានមេដាយសំរិទ្ធ',
      'achievements': 'សមិទ្ធផល',
      'it_department': 'ផ្នែកព័ត៌មានវិទ្យា',
      'acc_department': 'ផ្នែកគណនេយ្យ',
      'admin_department': 'ផ្នែករដ្ឋបាល',

      // in callender
      'no_data': 'គ្មានទិន្នន័យ',
      'total_work_hours': 'សរុបម៉ោងការងារ',
      'hours_unit': 'ម៉ោង',
      'attendance_calendar_title': 'ប្រតិទិនវត្តមាន',
      'download_report': 'កំពុងទាញយករបាយការណ៍...',
      'day_label': 'ថ្ងៃទី',
      'avg_attendance': 'មធ្យមភាគវត្តមាន',

      //face scanner screen
      'face_scan_title': 'សូមដាក់ផ្ទៃមុខឱ្យចំរង្វង់',
      'face_scan_step': 'ជំហានទី ២: ស្កេនផ្ទៃមុខ',
      'live_status': 'បន្តផ្ទាល់',
      'switch_camera': 'ប្តូរកាមេរ៉ា',
      'ensure_light': 'ធានាថាពន្លឺគ្រប់គ្រាន់',
      'scan_success': 'ស្កេនជោគជ័យ!',
      'camera_error': 'មានបញ្ហាកាមេរ៉ា',
    },
  };

  static String tr(String key) {
    return data[currentLang]?[key] ?? key;
  }
}
