import 'package:flutter_worksmart_mobile_app/config/language_manager.dart';

class AppStrings {
  static String get currentLang => LanguageManager().locale;

  static const Map<String, Map<String, String>> data = {
    'en': {
      // --- Menu ---
      'home_menu': 'Home',
      'atd_menu': 'Attendent',
      'leave_menu': 'Leave',
      'profile_menu': 'Profile',

      // --- Auth ---
      'logging_in_employee': 'Logging in to Employee account...',
      'logging_in_admin': 'Logging in to Admin account...',
      'smart_hr_system': 'Smart HR Management System',
      'admin_dashboard': 'Admin Dashboard',
      'welcome': 'Welcome',
      'admin_login_title': 'Admin Login',
      'smart_hr_management': 'Smart HR Management',
      'advanced_access': 'Advanced Access',
      'login_subtitle_employee': 'Log in to manage attendance and payroll',
      'login_subtitle_admin': 'Please verify your admin identity',
      'employee_tab': 'Employee',
      'admin_tab': 'Admin',
      'username': 'Username',
      'username_or_id': 'Username or ID',
      'enter_username': 'Enter username',
      'admin_id': 'Admin ID',
      'enter_id_hint': 'Enter ID',
      'enter_id_error': 'Please enter Username or ID',
      'password': 'Password',
      'enter_password': 'Enter password',
      'enter_password_hint': 'Enter Password',
      'enter_password_error': 'Please enter password',
      'password_length_error': 'Password must be at least 6 characters',
      'login': 'Login',
      'login_button': 'Login',
      'admin_login_button': 'Login as Admin',
      'finish': 'Finish',
      'invalid_credentials': 'Invalid username or password',
      'username_required': 'Username is required',
      'password_required': 'Password is required',
      'username_too_short': 'Username must be at least 2 characters',
      'password_too_short': 'Password must be at least 4 characters',
      'demo_credentials': 'Demo Credentials',
      'forgot_password': 'Forgot Password?',
      'app_version': 'WorkSmart v1.0 • ',
      "forgot_password_desc":
          "Please enter your email address to receive a verification code.",
      "email_label": "Email Address",
      "enter_email_error": "Please enter your email",
      "invalid_email_error": "Invalid email format",
      "send_button": "Send Code",
      "verify_title": "Verify Code",
      "otp_message": "We have sent a 4-digit code to your email address.",
      "verify_button": "Verify",
      "resend_code": "Resend Code",
      "verifying": "Verifying...",
      "otp_length_error": "Please enter all 4 digits",
      "reset_password_title": "Reset Password",
      "reset_password_subtitle": "Create a strong new password",
      "new_password_label": "New Password",
      "new_password_hint": "Enter new password",
      "confirm_password_label": "Confirm Password",
      "confirm_password_hint": "Re-enter new password",
      "password_empty_error": "Please enter password",
      "password_mismatch_error": "Passwords do not match",
      "change_password_button": "Change Password",
      "success_title": "Success!",
      "success_message": "Your password has been changed successfully.",
      "back_to_login": "Back to Login",

      // --- Tutorial ---
      'skip': 'Skip',
      'start': 'Start',
      'next': 'Next',
      'tutorial_title_1': 'Smart Attendance Management',
      'tutorial_subtitle_1': 'Track employee attendance safely and efficiently',
      'tutorial_title_2': 'Anti-Fraud Technology',
      'tutorial_subtitle_2':
          'Verify GPS location and live photo to ensure accuracy',
      'tutorial_title_3': 'Increase Work Efficiency',
      'tutorial_subtitle_3':
          'Achieve achievements and good ranking in the company',

      // --- Admin Tutorial ---
      'back': 'Back',
      'admin_tutorial_title_1': 'Welcome to Admin Dashboard',
      'admin_tutorial_subtitle_1':
          'Manage your entire workforce from one powerful interface. Monitor attendance, track performance, and make data-driven decisions.',
      'admin_tutorial_title_2': 'Employee Management',
      'admin_tutorial_subtitle_2':
          'View and manage all employee information, attendance records, leave requests, and performance metrics in real-time.',
      'admin_tutorial_title_3': 'Analytics & Reports',
      'admin_tutorial_subtitle_3':
          'Generate comprehensive reports with visual analytics. Track trends, identify patterns, and optimize workforce efficiency.',
      'admin_tutorial_title_4': 'System Configuration',
      'admin_tutorial_subtitle_4':
          'Customize settings, manage permissions, configure workflows, and maintain system security for your organization.',

      // --- Home & Map Status ---
      'greeting': 'Good Morning,',
      'safety': 'Safety',
      'greet_pronoun_man': 'Mr',
      'greet_pronoun_woman': 'Ms',
      'check_in': 'In',
      'check_out': 'Out',
      'work_hours': 'Hours',
      'current_loc': 'Current Location',
      'office_name': 'Phnom Penh Office',
      'leave_question': 'Time to leave work?',
      'in_range': 'In Range',
      'scan_out': 'Scan to Check Out',
      'annual_leave': 'Annual Leave',
      'sick_leave': 'Sick Leave',
      'employee_title': 'Employee of the Month',
      'view_all': 'View All',
      'role_trainer': 'Trainer',
      'role_ios': 'iOS Developer',
      'role_designer': 'Designer',
      'days': 'Days',
      'office_zone': 'Office Zone',
      'outside_zone': 'Outside Zone',
      'gps_status': 'GPS Status',
      'ready_to_scan': 'Ready to Scan',
      'too_far': 'Too Far',
      'distance': 'Distance',
      'get_directions': 'Get Directions',
      'finding_location': 'Finding location...',
      'perm_needed': 'Location permission needed',
      'enable_loc_settings': 'Please enable location in settings',
      'waiting_loc': 'Waiting for location...',
      'in_office_area': 'You are in the office area',
      'far_from_office': 'Away',
      'from_office': 'from office',
      'mock_date': 'Mon, 24 Oct 2023',
      'face_required_title': 'Please Verify Your Face',
      'face_required_desc':
          'Please press the button below to scan your face for attendance check-in',
      'register_now': 'Register Now',
      'waiting_admin': 'Waiting for Admin...',
      'pending_approval_title': 'Scan Under Review',
      'pending_approval_desc':
          'Your identity is being verified. Please wait for admin approval.',
      'processing': 'Processing...',
      'points_label': 'Pts',
      'punctuality': 'Punctuality',
      'search_by_employee_name_role_or_check_in_time':
          'Search by employee name, role, or check-in time...',
      'results_found': 'Results found',
      'try_searching_different_name_or_department':
          'Try searching for a different name or department.',

      // --- Attendance ---
      'my_stats': 'My Statistics',
      'attendance_rate': 'Attendance Rate',
      'present': 'Present',
      'late': 'Late',
      'absent': 'Absent',
      'monthly_trend': 'Monthly Attendance Trends',
      'all_shifts': 'All Shifts',
      'monthly_attendance': 'Monthly Attendance',
      'attendance_details': 'Attendance Details',
      'check_in_title': 'Check-In',
      'check_out_title': 'Check-Out',
      'total_hours': 'Total Work Hours',
      'equal_to': 'Equal to',
      'one_full_day': '1 Full Day',
      'on_time': 'On Time',
      'location_label': 'Location',
      'phnom_penh': 'Phnom Penh',
      'date_label': 'Date',
      'no_records': 'No records available',
      'no_data_for_today': 'No data for today',

      // --- Leave Management & Requests ---
      'leave_details_title': 'Leave Details',
      'usage_stats': 'Usage Statistics',
      'request_history': 'Request History',
      'you_have_remaining_leave': 'You have',
      'this_year': 'of leave remaining for this year.',
      'remaining': 'Remaining',
      'used': 'Used',
      'request_sick_leave': 'Request Sick Leave',
      'request_annual_leave': 'Request Annual Leave',
      'status_approved': 'Approved',
      'status_rejected': 'Rejected',
      'status_pending': 'Pending',
      'sick_leave_fever': 'Sick Leave (Fever)',
      'personal_leave': 'Personal Leave',
      'special_leave': 'Special Leave',
      'days_remaining': 'Days Remaining',
      'recent_requests': 'Recent Requests',
      'leave_request_details': 'Leave Request Details',

      // Annual Leave Request Screen
      'request_annual_leave_title': 'Annual Leave Request',
      'annual_leave_balance_msg':
          'You have 12 days of annual leave remaining for this year.',
      'select_date': 'Select Date',
      'start_date': 'Start Date',
      'end_date': 'End Date',
      'reason_for_request': 'Reason for Request',
      'enter_reason_hint': 'Enter reason here...',
      'submit_request': 'Submit Request',

      // Sick Leave Request Screen
      'request_sick_leave_title': 'Sick Leave Request',
      'leave_type': 'Leave Type',
      'sick_leave_type_label': 'Sick Leave',
      'request_details': 'Request Details',
      'reason_for_sickness': 'Reason for Sickness',
      'sickness_reason_hint': 'Describe symptoms...',
      'leave_date': 'Leave Date',
      'select_date_hint': 'Select Date',
      'medical_documents': 'Medical Documents',
      'attached_file': 'Attached File: ',
      'upload_medical_cert': 'Click here to upload medical certificate',
      'tap_to_change_file': 'Tap again to change file',
      'submit_official_request': 'Submit Official Request',

      // --- Notifications ---
      'notifications_title': 'Notifications',
      'mark_read': 'Mark as read',
            'mark_all_read': 'Mark all as read',
      'delete_notif': 'Delete this notification',
      'read_all': 'Read All',
      'no_notif': 'No notifications yet',
      'notif_deleted': 'Notification deleted',
      'leave_request': 'Leave Request',
      'leave_approved_msg': 'Your annual leave has been approved.',
      'time_ago_2h': '2 hours ago',

      // --- Leaderboard ---
      'top_rankings': 'Top Rankings',
      'monthly': 'Monthly',
      'yearly': 'Yearly',
      'next_rankings': 'Next Rankings',
      'average_score': 'Average Score',
      'next_goal': 'Next Goal',
      'goal_description': 'Reach 95% to receive a bronze medal',
      'achievements': 'Achievements',
      'it_department': 'IT Department',
      'acc_department': 'Accounting Department',
      'recognition_program': 'Recognition Program',
      'admin_department': 'Admin Department',

      // --- Achievement Screen ---
      'my_achievements': 'My Achievements',
      'hello': 'Hello',
      'role_it_staff': 'IT Staff',
      'total_medals': 'Total Medals',
      'rank_label': 'Rank',
      'earned_badges': 'Earned Badges',
      'progress': 'Progress',
      'goal_hero_desc': 'Continue 5 more days to get "Hero" medal',
      'badge_early_bird': 'Early Bird',
      'badge_perfect_atd': 'Perfect Attendance',
      'badge_emp_month': 'Employee of Month',
      'badge_speed': 'Fast Learner',
      'badge_collab': 'Good Teamwork',
      'badge_creative': 'Creative Mind',

      // --- Calendar ---
      'no_data': 'No Data',
      'total_work_hours': 'Total Work Hours',
      'hours_unit': 'Hours',
      'attendance_calendar_title': 'Attendance Calendar',
      'download_report': 'Downloading report...',
      'day_label': 'Day',
      'avg_attendance': 'Average Attendance',

      // --- Face Scan ---
      'face_scan_title': 'Please place your face in the circle',
      'face_scan_step': 'Next Step: Scan Face',
      'live_status': 'LIVE',
      'switch_camera': 'Switch',
      'ensure_light': 'Ensure enough light',
      'scan_success': 'Scan Success!',
      'camera_error': 'Camera Error',

      // --- Help & Support ---
      'help_support_title': 'Help & Support',
      'contact_us': 'Contact Us',
      'customer_service': 'Customer Service',
      'quick_response': 'Fast response 24/7',
      'send_email': 'Send Email',
      'faq_title': 'FAQ',
      'faq_change_pass': 'How to change password?',
      'faq_connect_tele': 'How to connect Telegram?',
      'faq_login_issue': 'Login issues',

      // --- Profile ---
      'account_title': 'Account',
      'choose_photo': 'Choose Photo',
      'gallery': 'Gallery',
      'camera': 'Camera',
      'phone_label': 'Phone Number',
      'not_connected': 'Not Connected',
      'connect_now': 'Connect Now',
      'change_password_action': 'Change Password',
      'logout_action': 'Logout',
      'confirm_logout_title': 'Logout Account',
      'confirm_logout_msg': 'Are you sure you want to logout?',
      'cancel_button': 'Cancel',
      'logout_button': 'Logout',

      // --- Settings ---
      'settings_title': 'Settings',
      'general_section': 'General',
      'language_label': 'Language',
      'dark_mode': 'Dark Mode',
      'notification_label': 'Notification',
      'support_section': 'Support',
      'about_app': 'About App',

      // --- Telegram Integration ---
      'telegram_setup_title': 'Telegram Setup',
      'connect_telegram_title': 'Connect with Telegram',
      'connect_telegram_desc':
          'Get instant notifications about work and attendance via Telegram Bot.',
      'connect_now_button': 'Connect Now ',
      'scan_qr_title': 'Scan QR to Join',
      'how_to_connect': 'How to connect:',
      'step_1_title': 'Scan QR Code',
      'step_1_desc': 'Open your phone camera to scan the code above.',
      'step_2_title': 'Press Start Button',
      'step_2_desc': 'Send /start message to the bot to register.',
      'step_3_title': 'Receive Notifications',
      'step_3_desc': 'You will receive automatic notifications via Telegram.',

      // --- Date & Time ---
      'month_jan': 'Jan',
      'month_feb': 'Feb',
      'month_mar': 'Mar',
      'month_apr': 'Apr',
      'month_may': 'May',
      'month_jun': 'Jun',
      'month_jul': 'Jul',
      'month_aug': 'Aug',
      'month_sep': 'Sep',
      'month_oct': 'Oct',
      'month_nov': 'Nov',
      'month_dec': 'Dec',
      'monday': 'Monday', 'tuesday': 'Tuesday', 'wednesday': 'Wednesday',
      'thursday': 'Thursday',
      'friday': 'Friday',
      'saturday': 'Saturday',
      'sunday': 'Sunday',

      'mock_gps_label': 'Mock GPS Detected!',
      'mock_gps_warning': 'Fake GPS Detected! Please disable mock location.',

      'face_training_title': 'Face ID Training',
      'take_photo_step': 'Step',
      'face_registered_success': 'Face registered successfully!',

      // --- Manage Users ---
      'manage_users_title': 'Manage Users',
      'manage_users_subtitle': 'View and manage system users',
      'create_user': 'Create User',
      'search_users_hint': 'Search by name, email, or ID...',
      'total_users': 'Total Users',
      'status_active': 'Active',
      'status_inactive': 'Inactive',
      'status_suspended': 'Suspended',
      'status_unknown': 'Unknown',
      'status_label': 'Status',
      'department_label': 'Department',
      'all': 'All',
      'all_departments': 'All Departments',
      'clear': 'Clear',
      'name_label': 'Name',

      'role_label': 'Role',
      'no_users_found': 'No users found',
      'edit': 'Edit',
      'delete': 'Delete',
      'user_settings_title': 'User Settings',
      'user_settings_subtitle': 'Modify permissions and status',
      'identity_section': 'IDENTITY',
      'account_status_section': 'ACCOUNT STATUS',
      'assigned_role_section': 'ASSIGNED ROLE',
      'enter_role_title': 'Enter role title...',
      'discard': 'Discard',
      'contact_section': 'Contact',
      'account_section': 'Account',
      'user_id_label': 'User ID',
      'office_label': 'Office',
      'face_status_label': 'Face Status',
      'join_date_label': 'Join Date',
      'close': 'Close',
      'identity_information': 'Identity Information',
      'create_user_title': 'Create New User',
      'create_user_subtitle': 'Enter details to onboard a new employee',
      'full_name_label': 'Full Name',
      'full_name_hint': 'e.g. Winner Yun',
      'name_required': 'Name is required',
      'role_title_label': 'Role Title',
      'role_title_hint': 'e.g. Senior Flutter Developer',
      'role_required': 'Role is required',
      'contact_system_section': 'Contact & System',
      'generated_auto': 'Generated automatically',
      'system_id_label': 'System ID (UID)',
      'not_available': 'N/A',
      'pending': 'Pending',
      'face_status_approved': 'Approved',
      'face_status_rejected': 'Rejected',
      'face_status_pending': 'Pending',

      // --- Admin Dashboard ---
      'real_time_attendance': 'Real-time Attendance',
      'live_checkin_stream': 'Live check-in stream',
      'employee': 'EMPLOYEE',
      'check_in_time': 'CHECK-IN',
      'selfie': 'SELFIE',
      'top_performers': 'Top Performers',
      'view_detailed_leaderboard': 'VIEW DETAILED LEADERBOARD',
      'active': 'ACTIVE',
      'total_employees': 'Total Employees',
      'top_talent': 'Top Talent',
      'improvement': 'Improvement',
      'search_hint': 'Search employees...',
      'present_today': 'Present Today',
      'checked_in': 'Checked in',
      'check_out_time': 'CHECK-OUT',
      'status': 'Status',
      'ontime_vs_late': 'On-time vs Late',
      'late_count': 'late',
      'pending_requests': 'Pending Requests',
      'requires_attention': 'Requires attention',
      'dashboard': 'Dashboard',
      'staff_management': 'Staff Management',
      'global_rank': 'Global Rank',
      'analytics': 'Analytics',
      'geofencing': 'Geofencing',
      'performance_leaderboard': 'Performance',
      'system_settings': 'System Settings',
      'admin_settings_subtitle':
          'Manage platform preferences and admin controls',
      'admin_settings_general': 'General',
      'admin_settings_general_subtitle': 'Language, region, and time format',
      'admin_settings_language': 'Language',
      'admin_settings_switch': 'Switch',
      'admin_settings_timezone': 'Timezone',
      'admin_settings_appearance': 'Appearance',
      'admin_settings_appearance_subtitle': 'Theme and layout preferences',
      'admin_settings_dark_mode': 'Dark mode',
      'admin_settings_dark_mode_desc': 'Reduce glare and save energy at night',
      'admin_settings_density': 'Density',
      'admin_settings_density_comfortable': 'Comfortable',
      'admin_settings_notifications': 'Notifications',
      'admin_settings_notifications_subtitle': 'Alerts and messaging controls',
      'admin_settings_enable_notifications': 'Enable notifications',
      'admin_settings_enable_notifications_desc':
          'Receive real-time admin alerts',
      'admin_settings_email_summaries': 'Email summaries',
      'admin_settings_email_summaries_desc':
          'Daily digest of attendance and leave',
      'admin_settings_security': 'Security',
      'admin_settings_security_subtitle': 'Access and approval workflows',
      'admin_settings_security_alerts': 'Security alerts',
      'admin_settings_security_alerts_desc':
          'Notify on unusual access activity',
      'admin_settings_auto_approve': 'Auto-approve low risk leave',
      'admin_settings_auto_approve_desc': 'Speed up approvals for short leaves',
      'admin_notif_view_all': 'View all',
      'admin_notif_late_title': 'Late check-in alert',
      'admin_notif_late_detail': '3 employees checked in late today',
      'admin_notif_leave_title': 'Leave request approved',
      'admin_notif_leave_detail': 'Sokha Vann: Annual leave approved',
      'admin_notif_attendance_title': 'New attendance record',
      'admin_notif_attendance_detail': '14 employees checked in this morning',
      'search_notifications': 'Search notifications...',
      'sort_asc': 'Ascending',
      'sort_desc': 'Descending',
      'performance_subtitle': 'Track and analyze employee performance rankings',
      'quarterly': 'Quarterly',
      'average_performance': 'Average Performance',
      'top_performer': 'Top Performer',
      'improved_count': 'Improved',
      'search_employee': 'Search employee name or ID...',
      'sort_by_score': 'Sort by Score',
      'sort_by_attendance': 'Sort by Attendance',
      'sort_by_medals': 'Sort by Medals',
      'no_employees_found': 'No employees found',
      'rank': 'Rank',
      'score': 'Score',
      'trend': 'Trend',
      'employee_id': 'Employee ID',
      'performance_score': 'Performance Score',
      'office_address': 'Office Address',
      'geofence_radius': 'Geofence Radius',
      'employees_in_range': 'Employees in Range',
      'office_locations': 'Office Locations',
      'manage_office_geofences': 'Manage geofences for offices',
      'search_offices': 'Search offices...',
      'no_offices_found': 'No offices found',
      'geofence_details': 'Geofence Details',
      'coordinates': 'Coordinates',
      'edit_geofence': 'Edit Geofence',
      'geofence_updated': 'Geofence updated successfully',
      'total_offices': 'Total Offices',
      'avg_radius': 'Avg Radius',
      'min_radius': 'Min Radius',
      'max_radius': 'Max Radius',
      'radius': 'Radius',
      'address_label': 'Address',
      'save': 'Save',
      'insights_overview': 'Performance Insights',
      'leave_summary': 'Leave Summary',
      'productivity_metrics': 'Productivity Metrics',
      'leaverequests': 'Leave Requests',
      'approved_requests': 'Approved Requests',
      'rejected_requests': 'Rejected Requests',
      'leave_requests': 'Leave Requests',
      'manage_employee_leave': 'Manage employee leave requests and approvals',
      'search_leave_requests': 'Search by employee name, ID, or leave type...',
      'dates': 'Dates',
      'reason': 'Reason',
      'approve': 'Approve',
      'reject': 'Reject',
      'no_requests_found': 'No leave requests found',
      'change_status_leave_request': 'Change the status of the leave request',
      'new_status': 'New Status',
      'search_and_filter_title': 'Search & Filter',
      'save_changes': 'Save Changes',
      'cancel': 'Cancel',

      // --- Geofencing Additional ---
      'geofencing_management': 'Geofencing Management',
      'geofencing_subtitle':
          'Define and manage geofenced areas for your offices to ensure secure and accurate attendance tracking.',
      'new_office': 'New Office',
      'select_office_view_details': 'Select an office to view details',
      'total_locations': 'Total Locations',
      'meter_unit': 'm',
      'adjust_geofence': 'Adjust Geofence',
      'geofence_updated_success': 'Geofence updated successfully!',
      'headquarters_example': 'e.g. Headquarters',
      'group_department': 'Group/Department',
      'engineering_example': 'e.g. Development Team',
      'office_name_required': 'Office name required',
      'group_name_required': 'Group name required',
      'location_selected': 'Location Selected',
      'set_office_location': 'Set Office Location',
      'latitude': 'Lat',
      'longitude': 'Lng',
      'max_range': 'Max Range',
      'tap_open_map': 'Tap to open interactive map',
      'create_new_office': 'Create New Office',
      'define_geofenced_area': 'Define a new geofenced area for your team.',
      'create_office': 'Create Office',
      'office_created_success': 'Office created successfully!',

      // --- Map Picker Dialog ---
      'select_office_location': 'Select Office Location',
      'search_or_click_map': 'Search or click on the map to pin point',
      'search_address': 'Search address...',
      'selected_location_label': 'Selected Location:',
      'confirm_location': 'Confirm Location',

      //--- Analytics ---
      'analytics_title': 'Workforce Analytics',
      'deep_dive_workforce_metrics':
          'Deep dive into workforce metrics and trends',
      'visual_breakdown': 'Visual breakdown',
      'period_week': 'Week',
      'period_month': 'Month',
      'period_quarter': 'Quarter',
      'card_total_staff': 'Total Staff',
      'card_active': 'Active Staff',
      'overview': 'OVERVIEW',
      'card_pending': 'Pending leave',
      'card_issues': 'Attendance issues',
      'card_presence_rate': 'Presence Rate',
      'card_total_absent': 'Total Absent',
      'card_late_arrivals': 'Late Arrivals',
      'card_employees': 'Employees',
      'card_avg_score': 'Avg Performance',
      'card_high_performers': 'High Performers',
      'card_improving': 'Improvement Needed',
      'card_low_performers': 'Low Performers',

      'month_january': 'January',
      'month_february': 'February',
      'month_march': 'March',
      'month_april': 'April',
      'month_mayy': 'May',
      'month_june': 'June',
      'month_july': 'July',
      'month_august': 'August',
      'month_september': 'September',
      'month_october': 'October',
      'month_november': 'November',
      'month_december': 'December',
    },
    'km': {
      // --- Menu ---
      'home_menu': 'ទំព័រដើម',
      'atd_menu': 'វត្តមាន',
      'leave_menu': 'ច្បាប់ឈប់សម្រាក',
      'profile_menu': 'ប្រវត្តិរូប',

      // --- Auth ---
      'logging_in_employee': 'កំពុងចូលក្នុងគណនីបុគ្គលិក...',
      'logging_in_admin': 'កំពុងចូលក្នុងគណនីអ្នកគ្រប់គ្រង...',
      'smart_hr_system': 'ប្រព័ន្ធគ្រប់គ្រងបុគ្គលិកវ័យឆ្លាត',
      'admin_dashboard': 'ផ្ទាំងគ្រប់គ្រងអ្នកគ្រប់គ្រង',
      'welcome': 'សូមស្វាគមន៍',
      'admin_login_title': 'ចូលជា Admin',
      'smart_hr_management': 'គ្រប់គ្រងធនធានមនុស្សបែបឆ្លាតវៃ',
      'advanced_access': 'ការចូលប្រើប្រាស់កម្រិតខ្ពស់',
      'login_subtitle_employee':
          'ចូលប្រព័ន្ធដើម្បីគ្រប់គ្រងវត្តមាន និងប្រាក់បៀវត្សរ៍',
      'login_subtitle_admin': 'សូមផ្ទៀងផ្ទាត់អត្តសញ្ញាណអ្នកគ្រប់គ្រងរបស់អ្នក',
      'employee_tab': 'បុគ្គលិក',
      'admin_tab': 'អ្នកគ្រប់គ្រង',
      'username': 'ឈ្មោះប្រើប្រាស់',
      'username_or_id': 'ឈ្មោះគណនី ឬ លេខសម្គាល់',
      'enter_username': 'បញ្ចូលឈ្មោះប្រើប្រាស់',
      'admin_id': 'គណនីអ្នកគ្រប់គ្រង (Admin ID)',
      'enter_id_hint': 'បញ្ចូលលេខសម្គាល់',
      'enter_id_error': 'សូមបញ្ចូលឈ្មោះគណនី ឬ លេខសម្គាល់',
      'password': 'ពាក្យសម្ងាត់',
      'enter_password': 'បញ្ចូលពាក្យសម្ងាត់',
      'enter_password_hint': 'បញ្ចូលពាក្យសម្ងាត់',
      'enter_password_error': 'សូមបញ្ចូលពាក្យសម្ងាត់',
      'password_length_error': 'ពាក្យសម្ងាត់ត្រូវមានយ៉ាងតិច ៦ ខ្ទង់',
      'login': 'ចូលប្រើប្រាស់',
      'login_button': 'ចូលប្រើប្រាស់',
      'admin_login_button': 'ចូលក្នុងនាមជា Admin',
      'finish': 'បញ្ចប់',
      'invalid_credentials': 'ឈ្មោះប្រើប្រាស់ ឬ ពាក្យសម្ងាត់មិនត្រឹមត្រូវ',
      'username_required': 'ឈ្មោះប្រើប្រាស់ត្រូវបាន តម្រូវ',
      'password_required': 'ពាក្យសម្ងាត់ត្រូវបាន តម្រូវ',
      'username_too_short': 'ឈ្មោះប្រើប្រាស់ត្រូវមានយ៉ាងតិច ២ តួអក្សរ',
      'password_too_short': 'ពាក្យសម្ងាត់ត្រូវមានយ៉ាងតិច ៤ តួអក្សរ',
      'demo_credentials': 'ស្គាល់ចម្លងលក្ខណៈលម្អិត',
      'forgot_password': 'ភ្លេចពាក្យសម្ងាត់?',
      'app_version': 'WorkSmart v1.0 • ',
      "forgot_password_desc":
          "សូមបញ្ចូលអាសយដ្ឋានអ៊ីមែលរបស់អ្នក ដើម្បីទទួលបានលេខកូដផ្ទៀងផ្ទាត់។",
      "email_label": "អាសយដ្ឋានអ៊ីមែល",
      "enter_email_error": "សូមបញ្ចូលអ៊ីមែលរបស់អ្នក",
      "invalid_email_error": "ទម្រង់អ៊ីមែលមិនត្រឹមត្រូវ",
      "send_button": "ផ្ញើលេខកូដ",
      "verify_title": "ផ្ទៀងផ្ទាត់កូដ",
      "otp_message": "យើងបានផ្ញើលេខកូដ ៤ ខ្ទង់ទៅកាន់អ៊ីមែលរបស់អ្នក។",
      "verify_button": "ផ្ទៀងផ្ទាត់",
      "resend_code": "ផ្ញើកូដម្តងទៀត",
      "verifying": "កំពុងផ្ទៀងផ្ទាត់...",
      "otp_length_error": "សូមបញ្ចូលកូដឱ្យបានគ្រប់ ៤ ខ្ទង់",
      "reset_password_title": "ប្តូរលេខសម្ងាត់",
      "reset_password_subtitle": "បង្កើតលេខសម្ងាត់ថ្មីដែលរឹងមាំ",
      "new_password_label": "លេខសម្ងាត់ថ្មី",
      "new_password_hint": "បញ្ចូលលេខសម្ងាត់ថ្មី",
      "confirm_password_label": "បញ្ជាក់លេខសម្ងាត់",
      "confirm_password_hint": "បញ្ចូលលេខសម្ងាត់ម្តងទៀត",
      "password_empty_error": "សូមបញ្ចូលលេខសម្ងាត់",
      "password_mismatch_error": "លេខសម្ងាត់មិនត្រូវគ្នា",
      "change_password_button": "ផ្លាស់ប្តូរលេខសម្ងាត់",
      "success_title": "ជោគជ័យ!",
      "success_message": "លេខសម្ងាត់របស់អ្នកត្រូវបានផ្លាស់ប្តូររួចរាល់ហើយ។",
      "back_to_login": "ត្រឡប់ទៅទំព័រចូល",

      // --- Tutorial ---
      'skip': 'រំលង',
      'start': 'ចាប់ផ្តើម',
      'next': 'បន្ទាប់',
      'tutorial_title_1': 'គ្រប់គ្រងវត្តមានដោយឆ្លាតវៃ',
      'tutorial_subtitle_1':
          'តាមដានវត្តមានបុគ្គលិកដោយសុវត្ថិភាព និងប្រសិទ្ធភាព',
      'tutorial_title_2': 'បច្ចេកវិទ្យាការពារការបន្លំ',
      'tutorial_subtitle_2':
          'ផ្ទៀងផ្ទាត់ទីតាំង GPS និងថតរូបផ្ទាល់ ដើម្បីធានាភាពត្រឹមត្រូវ',
      'tutorial_title_3': 'បង្កើនប្រសិទ្ធភាពការងារ',
      'tutorial_subtitle_3': 'ទទួលបានសមិទ្ធផល និងចំណាត់ថ្នាក់ល្អក្នុងក្រុមហ៊ុន',

      // --- Admin Tutorial ---
      'back': 'ត្រឡប់',
      'admin_tutorial_title_1': 'ស្វាគមន៍មកកាន់ផ្ទាំងគ្រប់គ្រង',
      'admin_tutorial_subtitle_1':
          'គ្រប់គ្រងបុគ្គលិកទាំងអស់របស់អ្នកពីចំណុចប្រទាក់ដ៏មានឥទ្ធិពលតែមួយ។ ត្រួតពិនិត្យវត្តមាន តាមដានការអនុវត្ត និងធ្វើការសម្រេចចិត្តផ្អែកលើទិន្នន័យ។',
      'admin_tutorial_title_2': 'គ្រប់គ្រងបុគ្គលិក',
      'admin_tutorial_subtitle_2':
          'មើល និងគ្រប់គ្រងព័ត៌មានបុគ្គលិកទាំងអស់ កំណត់ត្រាវត្តមាន សំណើច្បាប់ និងប្រវត្តិរូបការអនុវត្តក្នុងពេលវេលាជាក់ស្តែង។',
      'admin_tutorial_title_3': 'ការវិភាគ និងរបាយការណ៍',
      'admin_tutorial_subtitle_3':
          'បង្កើតរបាយការណ៍ពេញលេញជាមួយការវិភាគមើលឃើញ។ តាមដានទំនោរ កំណត់ទម្រង់ និងបង្កើនប្រសិទ្ធភាពកម្លាំងការងារ។',
      'admin_tutorial_title_4': 'ការកំណត់ប្រព័ន្ធ',
      'admin_tutorial_subtitle_4':
          'ប្តូរតាមបំណងការកំណត់ គ្រប់គ្រងសិទ្ធិ កំណត់ការដំណើរការ និងរក្សាសុវត្ថិភាពប្រព័ន្ធសម្រាប់ស្ថាប័នរបស់អ្នក។',

      // --- Home & Map Status ---
      'greeting': 'អរុណសួស្តី,',
      'safety': 'សុវត្ថិភាព',
      'check_in': 'ចូល',
      'check_out': 'ចេញ',
      'work_hours': 'ម៉ោង',
      'greet_pronoun_man': 'លោក',
      'greet_pronoun_woman': 'លោកស្រី',
      'current_loc': 'ទីតាំងបច្ចុប្បន្ន',
      'office_name': 'ការិយាល័យភ្នំពេញ',
      'leave_question': 'ដល់ពេលចេញពីធ្វើការ?',
      'in_range': 'ក្នុងទីតាំង',
      'scan_out': 'ចុះវត្តមានចេញ',
      'annual_leave': 'ច្បាប់ប្រចាំឆ្នាំ',
      'sick_leave': 'ច្បាប់ឈឺ',
      'employee_title': 'បុគ្គលិកឆ្នើម',
      'view_all': 'មើលទាំងអស់',
      'role_trainer': 'គ្រូបណ្តុះបណ្តាល',
      'role_ios': 'អ្នកអភិវឌ្ឍន៍ iOS',
      'role_designer': 'អ្នករចនា',
      'days': 'ថ្ងៃ',
      'office_zone': 'ក្នុងតំបន់ការិយាល័យ',
      'outside_zone': 'ក្រៅតំបន់ការិយាល័យ',
      'gps_status': 'ស្ថានភាព GPS',
      'ready_to_scan': 'អាចស្កេនបាន',
      'too_far': 'នៅឆ្ងាយពេក',
      'distance': 'ចម្ងាយ',
      'get_directions': 'នាំផ្លូវទៅកាន់ការិយាល័យ',
      'finding_location': 'កំពុងស្វែងរកទីតាំង...',
      'perm_needed': 'ត្រូវការការអនុញ្ញាតទីតាំង',
      'enable_loc_settings': 'សូមបើកសិទ្ធិទីតាំងនៅក្នុងការកំណត់',
      'waiting_loc': 'កំពុងរង់ចាំទីតាំង...',
      'in_office_area': 'អ្នកស្ថិតក្នុងបរិវេណការិយាល័យ',
      'far_from_office': 'នៅឆ្ងាយ',
      'from_office': 'ពីការិយាល័យ',
      'mock_date': 'ថ្ងៃចន្ទ, ២៤ តុលា ២០២៣',
      'face_required_title': 'សូមធ្វើការចុះអត្តសញ្ញាណមុខ',
      'face_required_desc':
          'សូមចុចប៊ូតុងខាងក្រោម ដើម្បីធ្វើការស្កេនមុខ សម្រាប់ការចុះវត្តមាន',
      'register_now': 'ចុះឈ្មោះឥឡូវនេះ',
      'waiting_admin': 'កំពុងរង់ចាំការអនុម័ត...',
      'pending_approval_title': 'កំពុងត្រួតពិនិត្យ',
      'pending_approval_desc':
          'អត្តសញ្ញាណរបស់អ្នកកំពុងត្រូវបានផ្ទៀងផ្ទាត់។ សូមរង់ចាំការអនុម័ត។',
      'processing': 'កំពុងដំណើរការ...',
      'points_label': 'ពិន្ទុ',
      'punctuality': 'ភាពទាន់ពេល',
      'search_by_employee_name_role_or_check_in_time':
          'ស្វែងរកដោយឈ្មោះបុគ្គលិក, តួនាទី, ឬ ពេលវេលាចុះវត្តមាន...',
      'results_found': 'លទ្ធផលដែលបានរកឃើញ',
      'try_searching_different_name_or_department':
          'សូមសាកល្បងស្វែងរកដោយឈ្មោះ ឬ ផ្នែកផ្សេងទៀត',

      // --- Attendance ---
      'my_stats': 'ស្ថិតិរបស់ខ្ញុំ',
      'attendance_rate': 'អត្រាវត្តមាន',
      'present': 'វត្តមាន',
      'late': 'មកយឺត',
      'absent': 'អវត្តមាន',
      'monthly_trend': 'និន្នាការវត្តមានប្រចាំខែ',
      'all_shifts': 'គ្រប់វេន',
      'monthly_attendance': 'វត្តមានប្រចាំខែ',
      'attendance_details': 'ព័ត៌មានលម្អិតនៃវត្តមាន',
      'check_in_title': 'ការចុះវត្តមានចូល',
      'check_out_title': 'ការចុះវត្តមានចេញ',
      'total_hours': 'សរុបម៉ោងការងារ',
      'equal_to': 'ស្មើនឹង',
      'one_full_day': '១ ថ្ងៃពេញ',
      'on_time': 'ទាន់ពេល',
      'location_label': 'ទីតាំង',
      'phnom_penh': 'ការិយាល័យកណ្ដាល',
      'date_label': 'កាលបរិច្ឆេទ',
      'no_records': 'មិនមានកំណត់ត្រាណាមួយ',
      'no_data_for_today': 'មិនមានទិន្នន័យសម្រាប់ថ្ងៃនេះទេ',

      // --- Leave Management & Requests ---
      'leave_details_title': 'ព័ត៌មានលម្អិតការឈប់សម្រាក',
      'usage_stats': 'ស្ថិតិប្រើប្រាស់',
      'request_history': 'ប្រវត្តិការស្នើសុំ',
      'you_have_remaining_leave': 'អ្នកនៅសល់ច្បាប់សម្រាកចំនួន',
      'this_year': 'សម្រាប់ឆ្នាំនេះ។',
      'remaining': 'នៅសល់',
      'used': 'ប្រើអស់',
      'request_sick_leave': 'ស្នើច្បាប់ឈឺ',
      'request_annual_leave': 'ស្នើច្បាប់ប្រចាំឆ្នាំ',
      'status_approved': 'បានអនុម័ត',
      'status_rejected': 'បានបដិសេធ',
      'status_pending': 'រង់ចាំ',
      'sick_leave_fever': 'ឈប់ច្បាប់ឈឺ (គ្រុនក្ដៅ)',
      'personal_leave': 'ឈប់សម្រាកផ្ទាល់ខ្លួន',
      'special_leave': 'ឈប់សម្រាកពិសេស',
      'days_remaining': 'ថ្ងៃនៅសល់',
      'recent_requests': 'សំណើថ្មីៗ',
      'leave_request_details': 'ព័ត៌មានលម្អិតនៃសំណើច្បាប់',

      // Annual Leave Request Screen
      'request_annual_leave_title': 'ពាក្យសុំច្បាប់ប្រចាំឆ្នាំ',
      'annual_leave_balance_msg':
          'អ្នកនៅសល់ច្បាប់សម្រាកចំនួន ១២ ថ្ងៃសម្រាប់ឆ្នាំនេះ។',
      'select_date': 'ជ្រើសរើសកាលបរិច្ឆេទ',
      'start_date': 'ថ្ងៃចាប់ផ្តើម',
      'end_date': 'ថ្ងៃបញ្ចប់',
      'reason_for_request': 'មូលហេតុនៃការស្នើសុំ',
      'enter_reason_hint': 'បញ្ជាក់មូលហេតុនៅទីនេះ...',
      'submit_request': 'ផ្ញើសំណើឈប់សម្រាក',

      // Sick Leave Request Screen
      'request_sick_leave_title': 'ពាក្យសុំច្បាប់ឈឺ',
      'leave_type': 'ប្រភេទច្បាប់',
      'sick_leave_type_label': 'ច្បាប់ឈឺ (Sick Leave)',
      'request_details': 'ព័ត៌មានលម្អិតនៃសំណើ',
      'reason_for_sickness': 'មូលហេតុនៃជំងឺ',
      'sickness_reason_hint': 'បញ្ជាក់ពីអាការៈជំងឺ...',
      'leave_date': 'កាលបរិច្ឆេទឈប់សម្រាក',
      'select_date_hint': 'ជ្រើសរើសថ្ងៃខែឆ្នាំ',
      'medical_documents': 'ឯកសារវេជ្ជសាស្ត្រ',
      'attached_file': 'ឯកសារភ្ជាប់៖ ',
      'upload_medical_cert': 'ចុចទីនេះដើម្បីភ្ជាប់លិខិតបញ្ជាក់ពីពេទ្យ',
      'tap_to_change_file': 'ចុចម្ដងទៀតដើម្បីប្ដូរឯកសារ',
      'submit_official_request': 'បញ្ជូនសំណើផ្លូវការ',

      // --- Notifications ---
      'notifications_title': 'ការជូនដំណឹង',
      'mark_read': 'សម្គាល់ថាបានអាន',
            'mark_all_read': 'សម្គាល់ថាបានអានទាំងអស់',
      'delete_notif': 'លុបការជូនដំណឹងនេះ',
      'read_all': 'អានទាំងអស់',
      'no_notif': 'មិនទាន់មានការជូនដំណឹងនៅឡើយទេ',
      'notif_deleted': 'បានលុបការជូនដំណឹង',
      'leave_request': 'ការស្នើសុំច្បាប់',
      'leave_approved_msg': 'ច្បាប់សម្រាកប្រចាំឆ្នាំរបស់អ្នកត្រូវបានអនុម័ត។',
      'time_ago_2h': '២ ម៉ោងមុន',

      // --- Leaderboard ---
      'top_rankings': 'ចំណាត់ថ្នាក់បុគ្គលិកឆ្នើម',
      'monthly': 'ប្រចាំខែ',
      'yearly': 'ប្រចាំឆ្នាំ',
      'next_rankings': 'ចំណាត់ថ្នាក់បន្ទាប់',
      'average_score': 'មធ្យមភាគពិន្ទុ',
      'next_goal': 'គោលដៅបន្ទាប់',
      'goal_description': 'ឈានដល់ ៩៥% ដើម្បីទទួលបានមេដាយសំរិទ្ធ',
      'achievements': 'សមិទ្ធផល',
      'it_department': 'ផ្នែកព័ត៌មានវិទ្យា',
      'acc_department': 'ផ្នែកគណនេយ្យ',
      'admin_department': 'ផ្នែករដ្ឋបាល',

      // --- Achievement Screen ---
      'my_achievements': 'សមិទ្ធផលរបស់ខ្ញុំ',
      'hello': 'សួស្តី',
      'role_it_staff': 'អ្នកបម្រើការផ្នែក IT',
      'total_medals': 'មេដាយសរុប',
      'rank_label': 'ចំណាត់ថ្នាក់',
      'earned_badges': 'មេដាយដែលទទួលបាន',
      'progress': 'វឌ្ឍនភាព',
      'goal_hero_desc': "បន្ត ៥ ថ្ងៃទៀតដើម្បីបានមេដាយ 'វីរៈបុរស'",
      'badge_early_bird': 'មកដល់មុនគេ',
      'badge_perfect_atd': 'វត្តមានឥតខ្ចោះ',
      'badge_emp_month': 'ឆ្នើមប្រចាំខែ',
      'badge_speed': 'លឿនរហ័ស',
      'badge_collab': 'សហការល្អ',
      'badge_creative': 'គំនិតច្នៃប្រឌិត',

      // --- Calendar ---
      'no_data': 'គ្មានទិន្នន័យ',
      'total_work_hours': 'សរុបម៉ោងការងារ',
      'hours_unit': 'ម៉ោង',
      'attendance_calendar_title': 'ប្រតិទិនវត្តមាន',
      'download_report': 'កំពុងទាញយករបាយការណ៍...',
      'day_label': 'ថ្ងៃទី',
      'avg_attendance': 'មធ្យមភាគវត្តមាន',

      // --- Face Scan ---
      'face_scan_title': 'សូមដាក់ផ្ទៃមុខឱ្យចំរង្វង់',
      'face_scan_step': 'ជំហានទី ២: ស្កេនផ្ទៃមុខ',
      'live_status': 'បន្តផ្ទាល់',
      'switch_camera': 'ប្តូរកាមេរ៉ា',
      'ensure_light': 'ធានាថាពន្លឺគ្រប់គ្រាន់',
      'scan_success': 'ស្កេនជោគជ័យ!',
      'camera_error': 'មានបញ្ហាកាមេរ៉ា',

      // --- Help & Support ---
      'help_support_title': 'ជំនួយ និង ការគាំទ្រ',
      'contact_us': 'ទំនាក់ទំនងមកយើង',
      'customer_service': 'ផ្នែកបម្រើអតិថិជន',
      'quick_response': 'ឆ្លើយតបរហ័ស ២៤/៧',
      'send_email': 'ផ្ញើអ៊ីមែល',
      'faq_title': 'សំណួរដែលសួរញឹកញាប់ (FAQ)',
      'faq_change_pass': 'របៀបប្តូរលេខសម្ងាត់?',
      'faq_connect_tele': 'តើធ្វើដូចម្តេចដើម្បីភ្ជាប់ Telegram?',
      'faq_login_issue': 'បញ្ហាការចុះឈ្មោះចូលប្រើប្រាស់',

      // --- Profile ---
      'account_title': 'គណនី',
      'choose_photo': 'ជ្រើសរើសរូបថត',
      'gallery': 'បណ្ណាល័យ',
      'camera': 'ម៉ាស៊ីនថត',
      'phone_label': 'លេខទូរស័ព្ទ',
      'not_connected': 'មិនទាន់ភ្ជាប់',
      'connect_now': 'ភ្ជាប់ឥឡូវ',
      'change_password_action': 'ប្តូរលេខសម្ងាត់',
      'logout_action': 'ចាកចេញពីគណនី',
      'confirm_logout_title': 'ចាកចេញពីគណនី',
      'confirm_logout_msg': 'តើអ្នកប្រាកដជាចង់ចាកចេញមែនទេ?',
      'cancel_button': 'បោះបង់',
      'logout_button': 'ចាកចេញ',

      // --- Settings ---
      'settings_title': 'ការកំណត់',
      'general_section': 'ទូទៅ',
      'language_label': 'ភាសា',
      'dark_mode': 'ផ្ទៃងងឹត',
      'notification_label': 'ការជូនដំណឹង',
      'support_section': 'គាំទ្រ',
      'about_app': 'អំពីកម្មវិធី',

      // --- Telegram Integration ---
      'telegram_setup_title': 'ការកំណត់ Telegram',
      'connect_telegram_title': 'ភ្ជាប់ជាមួយ Telegram',
      'connect_telegram_desc':
          'ទទួលបានការជូនដំណឹងភ្លាមៗអំពីការងារ និងវត្តមាន\nរបស់អ្នកតាមរយៈ Telegram Bot។',
      'connect_now_button': 'ភ្ជាប់ឥឡូវនេះ ',
      'scan_qr_title': 'ស្កេនកូដ QR ដើម្បីចូលរួម',
      'how_to_connect': 'របៀបភ្ជាប់៖',
      'step_1_title': 'ស្កេនកូដ QR',
      'step_1_desc': 'បើកកាមេរ៉ាទូរស័ព្ទរបស់អ្នក ដើម្បីស្កេនកូដខាងលើ។',
      'step_2_title': 'ចុចប៊ូតុង ចាប់ផ្តើម (Start)',
      'step_2_desc': 'ផ្ញើសារ /start ទៅកាន់ប៊ូត ដើម្បីធ្វើការចុះឈ្មោះ។',
      'step_3_title': 'ទទួលបានការជូនដំណឹង',
      'step_3_desc': 'អ្នកនឹងទទួលបានការជូនដំណឹងដោយស្វ័យប្រវត្តិតាម Telegram។',

      // --- Date & Time ---
      'month_jan': 'មករា',
      'month_feb': 'កុម្ភៈ',
      'month_mar': 'មីនា',
      'month_apr': 'មេសា',
      'month_may': 'ឧសភា',
      'month_jun': 'មិថុនា',
      'month_jul': 'កក្កដា',
      'month_aug': 'សីហា',
      'month_sep': 'កញ្ញា',
      'month_oct': 'តុលា',
      'month_nov': 'វិច្ឆិកា',
      'month_dec': 'ធ្នូ',
      'monday': 'ថ្ងៃច័ន្ទ', 'tuesday': 'ថ្ងៃអង្គារ', 'wednesday': 'ថ្ងៃពុធ',
      'thursday': 'ថ្ងៃព្រហស្បតិ៍',
      'friday': 'ថ្ងៃសុក្រ',
      'saturday': 'ថ្ងៃសៅរ៍',
      'sunday': 'ថ្ងៃអាទិត្យ',

      'mock_gps_label': 'ប្រព័ន្ធ GPS ក្លែងក្លាយ!',
      'mock_gps_warning': 'រកឃើញការបន្លំ GPS! សូមបិទការកំណត់ទីតាំងក្លែងក្លាយ។',

      'face_training_title': 'ការបង្វឹក Face ID',
      'take_photo_step': 'ជំហាន',
      'face_registered_success': 'ការចុះឈ្មោះផ្ទៃមុខបានជោគជ័យ!',

      // --- Admin Dashboard ---
      'real_time_attendance': 'វត្តមានក្នុងពេលវេលាជាក់ស្តែង',
      'live_checkin_stream': 'វិធានបង្ហាញវត្តមានផ្ទាល់',
      'employee': 'បុគ្គលិក',
      'check_in_time': 'ពេលចូល',
      'selfie': 'រូបថត',
      'top_performers': 'អ្នកអនុវត្តល្អបំផុត',
      'view_detailed_leaderboard': 'មើលលម្អិតចំណាត់ថ្នាក់',
      'active': 'ដំណើរការ',
      'search_hint': 'ស្វែងរកបុគ្គលិក...',
      'total_employees': 'សរុបបុគ្គលិក',
      'top_talent': 'បុគ្គលិកឆ្នើម',
      'improvement': 'បុគ្គលិកមានការកែលម្អ',
      'present_today': 'វត្តមានថ្ងៃនេះ',
      'checked_in': 'បានចូល',
      'check_out_time': 'ពេលចាកចេញ',
      'status': 'ស្ថានភាព',
      'ontime_vs_late': 'ទាន់ពេល ធៀបនឹង មកយឺត',
      'late_count': 'មកយឺត',
      'pending_requests': 'សំណើរង់ចាំ',
      'requires_attention': 'ទាមទារការយកចិត្តទុកដាក់',
      'dashboard': 'ផ្ទាំងគ្រប់គ្រង',
      'staff_management': 'ការគ្រប់គ្រងបុគ្គលិក',
      'global_rank': 'ចំណាត់ថ្នាក់សរុប',
      'analytics': 'ការវិភាគ',
      'geofencing': 'Geofencing',
      'performance_leaderboard': 'ចំណាត់ថ្នាក់ការអនុវត្ត',
      'system_settings': 'ការកំណត់ប្រព័ន្ធ',
      'admin_settings_subtitle':
          'គ្រប់គ្រងការកំណត់ និងការត្រួតពិនិត្យសម្រាប់អ្នកគ្រប់គ្រង',
      'admin_settings_general': 'ការកំណត់ទូទៅ',
      'admin_settings_general_subtitle': 'ភាសា តំបន់ និងទ្រង់ទ្រាយពេលវេលា',
      'admin_settings_language': 'ភាសា',
      'admin_settings_switch': 'ប្ដូរ',
      'admin_settings_timezone': 'តំបន់ពេលវេលា',
      'admin_settings_appearance': 'រូបរាង',
      'admin_settings_appearance_subtitle': 'រចនាប័ទ្ម និងការបង្ហាញ',
      'admin_settings_dark_mode': 'របៀបងងឹត',
      'admin_settings_dark_mode_desc':
          'បន្ថយការប៉ះពាល់ដល់ភ្នែក និងសន្សំថាមពលនៅពេលយប់',
      'admin_settings_density': 'កម្រិតបង្ហាញខ្លឹមសារ',
      'admin_settings_density_comfortable': 'ងាយស្រួលមើល',
      'admin_settings_notifications': 'ការជូនដំណឹង',
      'admin_settings_notifications_subtitle': 'ការជូនដំណឹង និងការគ្រប់គ្រងសារ',
      'admin_settings_enable_notifications': 'បើកការជូនដំណឹង',
      'admin_settings_enable_notifications_desc':
          'ទទួលការជូនដំណឹងពីប្រព័ន្ធអ្នកគ្រប់គ្រងភ្លាមៗ',
      'admin_settings_email_summaries': 'សេចក្ដីសង្ខេបតាមអ៊ីមែល',
      'admin_settings_email_summaries_desc':
          'ទទួលសេចក្ដីសង្ខេបប្រចាំថ្ងៃអំពីវត្តមាន និងការឈប់សម្រាក',
      'admin_settings_security': 'សុវត្ថិភាព',
      'admin_settings_security_subtitle': 'ការចូលប្រើ និងដំណើរការអនុម័ត',
      'admin_settings_security_alerts': 'ការជូនដំណឹងសុវត្ថិភាព',
      'admin_settings_security_alerts_desc':
          'ជូនដំណឹងនៅពេលមានការចូលប្រើមិនប្រក្រតី',
      'admin_settings_auto_approve':
          'អនុម័តស្វ័យប្រវត្តិសម្រាប់សំណើឈប់សម្រាកហានិភ័យទាប',
      'admin_settings_auto_approve_desc':
          'បង្កើនល្បឿនដំណើរការអនុម័តសម្រាប់សំណើខ្លីៗ',
      'admin_notif_view_all': 'មើលទាំងអស់',
      'admin_notif_late_title': 'ការជូនដំណឹងមកយឺត',
      'admin_notif_late_detail': 'បុគ្គលិក 3 នាក់បានចូលយឺតថ្ងៃនេះ',
      'admin_notif_leave_title': 'សំណើឈប់សម្រាកបានអនុម័ត',
      'admin_notif_leave_detail':
          'សុខា វណ្ណ៖ ច្បាប់ឈប់សម្រាកប្រចាំឆ្នាំបានអនុម័ត',
      'admin_notif_attendance_title': 'កំណត់ត្រាវត្តមានថ្មី',
      'admin_notif_attendance_detail': 'បុគ្គលិក 14 នាក់បានចូលការងារព្រឹកនេះ',
      'search_notifications': 'ស្វែងរកការជូនដំណឹង...',
      'sort_asc': 'ឡើងតាមលំដាប់',
      'sort_desc': 'ចុះតាមលំដាប់',

      'performance_subtitle': 'តាមដាន និងវិភាគចំណាត់ថ្នាក់ការអនុវត្តបុគ្គលិក',
      'quarterly': 'ត្រីមាស',
      'average_performance': 'ការអនុវត្តមធ្យម',
      'top_performer': 'អ្នកអនុវត្តល្អបំផុត',
      'improved_count': 'កែលម្អ',
      'search_employee': 'ស្វែងរកឈ្មោះ ឬលេខសម្គាល់បុគ្គលិក...',
      'sort_by_score': 'តម្រៀបតាមពិន្ទុ',
      'sort_by_attendance': 'តម្រៀបតាមវត្ដមាន',
      'sort_by_medals': 'តម្រៀបតាមមេដាយ',
      'no_employees_found': 'មិនរកឃើញបុគ្គលិក',
      'rank': 'ចំណាត់ថ្នាក់',
      'score': 'ពិន្ទុ',
      'trend': 'និន្នាការ',
      'employee_id': 'លេខសម្គាល់បុគ្គលិក',
      'performance_score': 'ពិន្ទុការអនុវត្ត',
      'office_address': 'អាសយដ្ឋានការិយាល័យ',
      'geofence_radius': 'កាំវិសាលភាពតំបន់',
      'employees_in_range': 'បុគ្គលិកក្នុងតំបន់',
      'office_locations': 'ទីតាំងការិយាល័យ',
      'manage_office_geofences': 'គ្រប់គ្រង geofences សម្រាប់ការិយាល័យ',
      'search_offices': 'ស្វែងរកការិយាល័យ...',
      'no_offices_found': 'មិនរកឃើញការិយាល័យ',
      'geofence_details': 'សម្បត្តិលម្អិត Geofence',
      'coordinates': 'កូអរដោនេ',
      'edit_geofence': 'កែសម្រួល Geofence',
      'geofence_updated': 'Geofence បានធ្វើបច្ចុប្បន្នភាពដោយជោគជ័យ',
      'total_offices': 'សរុបការិយាល័យ',
      'avg_radius': 'កាំមធ្យម',
      'min_radius': 'កាំអប្បបរមា',
      'max_radius': 'កាំអតិបរមា',
      'radius': 'កាំ',
      'address_label': 'អាសយដ្ឋាន',
      'save': 'រក្សាទុក',
      'insights_overview': 'ការវិភាគលម្អិត',
      'leave_summary': 'សង្ខេបច្បាប់ឈប់សម្រាក',
      'productivity_metrics': 'ម៉ែត្របី្របិយភាព',
      'leaverequests': 'សំណើច្បាប់ឈប់សម្រាក',
      'approved_requests': 'សំណើដែលបានអនុម័ត',
      'rejected_requests': 'សំណើដែលបានបដិសេធ',
      'leave_requests': 'សំណើច្បាប់ឈប់សម្រាក',
      'manage_employee_leave': 'គ្រប់គ្រងសំណើច្បាប់ឈប់សម្រាក និងការអនុម័ត',
      'search_leave_requests':
          'ស្វែងរកតាមឈ្មោះបុគ្គលិក អត្តលេខ ឬប្រភេទច្បាប់ឈប់សម្រាក...',
      'dates': 'កាលបរិច្ឆេទ',
      'reason': 'ហេតុផល',
      'approve': 'អនុម័ត',
      'reject': 'បដិសេធ',
      'no_requests_found': 'រកមិនឃើញសំណើច្បាប់ឈប់សម្រាក',
      'change_status_leave_request': 'ប្រែប្រែស្ថានភាពសំណើច្បាប់ឈប់សម្រាក',
      'new_status': 'ស្ថានភាពថ្មី',
      'save_changes': 'រក្សាទុកការផ្លាស់ប្តូរ',
      'cancel': 'បោះបង់',

      // --- Geofencing Additional ---
      'geofencing_management': 'ការគ្រប់គ្រង Geofence',
      'geofencing_subtitle':
          'កំណត់ និងគ្រប់គ្រងតំបន់ភូមិសាស្ត្រសម្រាប់ការិយាល័យរបស់អ្នក',
      'new_office': 'ការិយាល័យថ្មី',
      'select_office_view_details': 'ជ្រើសរើសការិយាល័យដើម្បីមើលលម្អិត',
      'total_locations': 'ទីតាំងសរុប',
      'meter_unit': 'm',
      'adjust_geofence': 'Geofence',
      'geofence_updated_success': 'Geofence បានធ្វើបច្ចុប្បន្នភាពដោយជោគជ័យ!',
      'headquarters_example': 'ឧ. Headquarters',
      'group_department': 'ក្រុម/ផ្នែក',
      'engineering_example': 'ឧ. Development Team',
      'office_name_required': 'ឈ្មោះការិយាល័យត្រូវបានទាមទារ',
      'group_name_required': 'ឈ្មោះក្រុមត្រូវបានទាមទារ',
      'location_selected': 'ទីតាំងបានជ្រើសរើស',
      'set_office_location': 'កំណត់ទីតាំងការិយាល័យ',
      'latitude': 'រយៈទទឹង',
      'longitude': 'រយៈបណ្តោយ',
      'max_range': 'កាំអតិបរមា',
      'tap_open_map': 'ចុចដើម្បីបើកផែនទី',
      'create_new_office': 'បង្កើតការិយាល័យថ្មី',
      'define_geofenced_area':
          'កំណត់ផ្ទៃដីវិស័យភូមិសាស្ត្រថ្មីសម្រាប់ក្រុមរបស់អ្នក។',
      'create_office': 'បង្កើតការិយាល័យ',
      'office_created_success': 'ការិយាល័យបានបង្កើតដោយជោគជ័យ!',

      // --- Map Picker Dialog ---
      'select_office_location': 'ជ្រើសរើសទីតាំងការិយាល័យ',
      'search_or_click_map': 'ស្វែងរក ឬចុចលើផែនទីដើម្បីចាប់ពិន្ទុ',
      'search_address': 'ស្វែងរកលម្អិត...',
      'selected_location_label': 'ទីតាំងដែលបានជ្រើសរើស:',
      'confirm_location': 'បញ្ជាក់ទីតាំង',

      // --- Manage Users ---
      'manage_users_title': 'គ្រប់គ្រងអ្នកប្រើប្រាស់',
      'manage_users_subtitle': 'មើល និងគ្រប់គ្រងអ្នកប្រើប្រាស់ប្រព័ន្ធ',
      'create_user': 'បង្កើតអ្នកប្រើប្រាស់',
      'search_users_hint': 'ស្វែងរកតាមឈ្មោះ អ៊ីមែល ឬអត្តលេខ...',
      'total_users': 'អ្នកប្រើប្រាស់សរុប',
      'status_active': 'សកម្ម',
      'status_inactive': 'អសកម្ម',
      'status_suspended': 'ផ្អាក',
      'status_unknown': 'មិនស្គាល់',
      'status_label': 'ស្ថានភាព',
      'department_label': 'ផ្នែក',
      'all': 'ទាំងអស់',
      'all_departments': 'ផ្នែកទាំងអស់',
      'clear': 'សម្អាត',
      'name_label': 'ឈ្មោះ',

      'role_label': 'តួនាទី',
      'no_users_found': 'រកមិនឃើញអ្នកប្រើប្រាស់',
      'edit': 'កែប្រែ',
      'delete': 'លុប',
      'user_settings_title': 'ការកំណត់អ្នកប្រើប្រាស់',
      'user_settings_subtitle': 'កែប្រែសិទ្ធិ និងស្ថានភាព',
      'identity_section': 'អត្តសញ្ញាណ',
      'account_status_section': 'ស្ថានភាពគណនី',
      'assigned_role_section': 'តួនាទីដែលបានកំណត់',
      'enter_role_title': 'បញ្ចូលតួនាទី...',
      'discard': 'បោះបង់',
      'contact_section': 'ទំនាក់ទំនង',
      'account_section': 'គណនី',
      'user_id_label': 'អត្តលេខ',
      'office_label': 'ការិយាល័យ',
      'face_status_label': 'ស្ថានភាពមុខ',
      'join_date_label': 'ថ្ងៃចូលធ្វើការ',
      'close': 'បិទ',
      'identity_information': 'ព័ត៌មានអត្តសញ្ញាណ',
      'create_user_title': 'បង្កើតអ្នកប្រើប្រាស់ថ្មី',
      'create_user_subtitle': 'បញ្ចូលព័ត៌មានដើម្បីបន្ថែមបុគ្គលិកថ្មី',
      'full_name_label': 'ឈ្មោះពេញ',
      'full_name_hint': 'ឧ. Winner Yun',
      'name_required': 'ត្រូវបញ្ចូលឈ្មោះ',
      'role_title_label': 'តួនាទីការងារ',
      'role_title_hint': 'ឧ. Senior Flutter Developer',
      'role_required': 'ត្រូវបញ្ចូលតួនាទី',
      'contact_system_section': 'ទំនាក់ទំនង និងប្រព័ន្ធ',
      'generated_auto': 'បង្កើតដោយស្វ័យប្រវត្តិ',
      'system_id_label': 'លេខប្រព័ន្ធ (UID)',
      'not_available': 'មិនមាន',
      'pending': 'កំពុងរង់ចាំ',
      'face_status_approved': 'បានអនុម័ត',
      'search_and_filter_title': 'ស្វែងរក និងតម្រៀប',
      'face_status_rejected': 'បានបដិសេធ',
      'face_status_pending': 'កំពុងរង់ចាំ',

      //--- Analytics ---
      'analytics_title': 'វិភាគកម្លាំងការងារ',
      'deep_dive_workforce_metrics':
          'វិភាគលម្អិតអំពីសូចនាករ និងនិន្នាការកម្លាំងការងារ',
      'visual_breakdown': 'ការបង្ហាញជាតារាងក្រាហ្វិក',
      'period_week': 'ប្រចាំសប្តាហ៍',
      'period_month': 'ប្រចាំខែ',
      'period_quarter': 'ប្រចាំត្រីមាស',
      'card_total_staff': 'ចំនួនបុគ្គលិកសរុប',
      'card_active': 'បុគ្គលិកកំពុងបំពេញការងារ',
      'overview': 'ទិដ្ឋភាពទូទៅ',
      'card_pending': 'ការឈប់សម្រាកកំពុងរង់ចាំអនុម័ត',
      'card_issues': 'បញ្ហាវត្តមាន',
      'card_presence_rate': 'អត្រាវត្តមាន',
      'card_total_absent': 'ចំនួនអវត្តមានសរុប',
      'card_late_arrivals': 'ការមកយឺត',
      'card_employees': 'បុគ្គលិក',
      'card_avg_score': 'ពិន្ទុប្រសិទ្ធភាពមធ្យម',
      'card_high_performers': 'បុគ្គលិកប្រសិទ្ធភាពខ្ពស់',
      'card_improving': 'ត្រូវការកែលម្អ',
      'card_low_performers': 'បុគ្គលិកប្រសិទ្ធភាពទាប',

      'month_january': 'មករា',
      'month_february': 'កុម្ភៈ',
      'month_march': 'មីនា',
      'month_april': 'មេសា',
      'month_mayy': 'ឧសភា',
      'month_june': 'មិថុនា',
      'month_july': 'កក្កដា',
      'month_august': 'សីហា',
      'month_september': 'កញ្ញា',
      'month_october': 'តុលា',
      'month_november': 'វិច្ឆិកា',
      'month_december': 'ធ្នូ',
    },
  };

  static String tr(String key) {
    return data[currentLang]?[key] ?? key;
  }
}
